Enable interpreting HPC coordinates as on the inside of a spherical screen
sunpy/sunpy pull request #4003
Opened 2020-04-08 14:08 UTC by ayshih

We normally interpret Helioprojective (HPC) 2D coordinates as being on the surface of the Sun.
This PR adds a context manager to instead interpret HPC 2D coordinates as on the inside of a spherical screen.  The center of the spherical screen is user-supplied, and the radius of the screen is the distance between the supplied center and Sun center.  One can also optionally choose (using the keyword `only_off_disk`) to have this overriding assumption apply only to off-disk coordinates, with on-disk coordinates still being on the surface of the Sun.

## Simple examples
```python
>>> import astropy.units as u
>>> from sunpy.coordinates import Helioprojective
>>> h = Helioprojective(range(7)*u.arcsec*319, [0]*7*u.arcsec, observer='earth', obstime='2020-04-08')
>>> print(h.make_3d())
<Helioprojective Coordinate (obstime=2020-04-08T00:00:00.000, rsun=695700.0 km, observer=<HeliographicStonyhurst Coordinate for 'earth'>): (Tx, Ty, distance) in (arcse
c, arcsec, AU)
    [(   0., 0., 0.99660825), ( 319., 0., 0.99687244),
     ( 638., 0., 0.99778472), ( 957., 0., 1.00103285),
     (1276., 0.,        nan), (1595., 0.,        nan),
     (1914., 0.,        nan)]>

>>> with Helioprojective.assume_spherical_screen(h.observer):
...     print(h.make_3d())
<Helioprojective Coordinate (obstime=2020-04-08T00:00:00.000, rsun=695700.0 km, observer=<HeliographicStonyhurst Coordinate for 'earth'>): (Tx, Ty, distance) in (arcse
c, arcsec, AU)
    [(   0., 0., 1.00125872), ( 319., 0., 1.00125872),
     ( 638., 0., 1.00125872), ( 957., 0., 1.00125872),
     (1276., 0., 1.00125872), (1595., 0., 1.00125872),
     (1914., 0., 1.00125872)]>

>>> with Helioprojective.assume_spherical_screen(h.observer, only_off_disk=True):
...     print(h.make_3d())
<Helioprojective Coordinate (obstime=2020-04-08T00:00:00.000, rsun=695700.0 km, observer=<HeliographicStonyhurst Coordinate for 'earth'>): (Tx, Ty, distance) in (arcse
c, arcsec, AU)
    [(   0., 0., 0.99660825), ( 319., 0., 0.99687244),
     ( 638., 0., 0.99778472), ( 957., 0., 1.00103285),
     (1276., 0., 1.00125872), (1595., 0., 1.00125872),
     (1914., 0., 1.00125872)]>
```

## Examples using `reproject`
```python
aia_map = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
...
with Helioprojective.assume_spherical_screen(aia_map.observer_coordinate):
    output, _ = reproject_interp(...)
```
or
```python
with Helioprojective.assume_spherical_screen(aia_map.observer_coordinate, only_off_disk=True):
    output, _ = reproject_interp(...)
```

![screen](https://user-images.githubusercontent.com/991759/78792054-a20fb500-797e-11ea-8b28-a2a91eb6392e.png)

2020-04-08 15:42 UTC, ayshih commented
Per the request in #3997, here are reprojections of LASCO C2 and C3 images using `only_off_disk=True`.  Note that the Sun is the black hemisphere that is blocking part of the reprojected images.

![lasco](https://user-images.githubusercontent.com/991759/78804316-fd956f00-798d-11ea-9d18-58bbdaac9e72.png)

2020-04-09 00:53 UTC, ayshih commented
@wafels asked:

> Quick question - for the spherical screen, isn't the distance 'd' between the observer and a point on the screen always the same as the distance between the observer and sun center?

When the specified center of the spherical screen is precisely the observer, yes, you could just set all of the `distance` components to be the Sun-observer distance.  Admittedly, my "simple examples" are all this special case.

However, for the reprojection to work, what is needed is to specify the center of the spherical screen to be the observer of the source frame, which means it is *not* the same as the observer of the destination frame.  (The context manager overrides the `.make_3d()` method of both the source and destination frames.)  Thus, that's why there's the non-trivial code (law of cosines) to compute the distance component in the destination frame.

2020-04-13 19:21 UTC, pep8speaks commented
Hello @ayshih! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`sunpy/coordinates/frames.py`](https://github.com/sunpy/sunpy/blob/fa3b9ab53890bd8a2cdeaa1d1326cfbb6752580f/sunpy/coordinates/frames.py):

> [Line 537:101](https://github.com/sunpy/sunpy/blob/fa3b9ab53890bd8a2cdeaa1d1326cfbb6752580f/sunpy/coordinates/frames.py#L537): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (189 > 100 characters)
> [Line 544:101](https://github.com/sunpy/sunpy/blob/fa3b9ab53890bd8a2cdeaa1d1326cfbb6752580f/sunpy/coordinates/frames.py#L544): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (189 > 100 characters)

2020-09-29 13:21 UTC, Cadair commented
I am ok with this as long as it comes with sufficient health warnings. It's certainly neat as a visualisation tool if nothing else.

2020-11-17 15:12 UTC, kakirastern approved these changes
Looks good

2020-11-18 17:06 UTC, Cadair requested changes
Looks good other than the example needs updating for #4620

2020-11-18 17:59 UTC, ayshih commented on examples/map_transformations/reprojection_spherical_screen.py
> +out_wcs.heliographic_observer = new_observer
Fixed

2020-11-18 23:40 UTC, Cadair approved these changes

2020-11-18 23:40 UTC, Cadair commented
Why is codecov angry? Is this in need of some tests @ayshih ?

2020-11-18 23:41 UTC, nabobalis commented
> Why is codecov angry? Is this in need of some tests @ayshih ?

Azure didn't run.

2020-11-19 00:16 UTC, kakirastern commented
Uh oh

2020-11-19 04:57 UTC, ayshih commented
Kicked Azure, now all green

2020-11-19 04:59 UTC, kakirastern commented
🎉

2020-11-19 05:25 UTC, kakirastern commented
@nabobalis Please merge when the PR's ready

2020-11-19 09:28 UTC, merged