check iso format instead
sunpy/sunpy pull request #4560
Opened 2020-10-11 08:46 UTC by nabobalis

2020-10-11 19:56 UTC, dstansby requested changes
Although this fixes the tests, I think we should understand what's going on. Could you print `time.jd1` and `time.jd2` for a test that fails so we can see the difference in the underlying time values?

2020-10-11 21:54 UTC, nabobalis commented
Had to go around about way to get logging/printing working with xdist.

2020-10-11 21:58 UTC, nabobalis commented on tox.ini
> +    # capture any logging we might put in a test for debugging.
```suggestion
    # xdist uses stdout in order to work, we bypass this to
    # allow logging in tests.
```

2020-10-11 22:06 UTC, nabobalis commented
```python


    def test_differential_rotate_observer_full_disk(aia171_test_map):
        # Test a full disk map
        new_observer = get_earth(aia171_test_map.date + 6*u.hr)
        dmap = differential_rotate(aia171_test_map, observer=new_observer)
        assert dmap.data.shape == aia171_test_map.data.shape
        logging.warning(f"{dmap.date.jd1}, {dmap.date.jd2}")
        logging.warning(f"{new_observer.obstime.jd1}, {new_observer.obstime.jd2}")
>       assert dmap.date == new_observer.obstime
E       AssertionError: assert <Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340> == <Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>
E         +<Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>
E         -<Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>

../../.tox/py38-32bit/lib/python3.8/site-packages/sunpy/physics/tests/test_differential_rotation.py:195: AssertionError
-------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------
WARNING  sunpy:test_differential_rotation.py:193 2455608.0, -0.24999606481481476
WARNING  sunpy:test_differential_rotation.py:194 2455608.0, -0.24999606481481465
_____________________________________________________________________ test_differential_rotate_time_full_disk ______________________________________________________________________
[gw3] linux -- Python 3.8.6 /project/.tox/py38-32bit/bin/python

aia171_test_map = <sunpy.map.sources.sdo.AIAMap object at 0xe6536190>
SunPy Map
---------
Observatory:		 SDO
Instrument:		 AIA 3
Detecto...0.  ],
       [-0.25,  0.  , -0.5 , ...,  0.75, -0.75,  0.  ],
       [ 0.75,  1.5 , -0.75, ...,  0.  , -0.5 ,  0.5 ]])

    def test_differential_rotate_time_full_disk(aia171_test_map):
        # Test a full disk map
        new_time = aia171_test_map.date + 6*u.hr
        with pytest.warns(UserWarning, match="Using 'time' assumes an Earth-based observer"):
            dmap = differential_rotate(aia171_test_map, time=new_time)
        assert dmap.data.shape == aia171_test_map.data.shape
        # The output map should have the same time as the new time now.
        logging.warning(f"{dmap.date.jd1}, {dmap.date.jd2}")
        logging.warning(f"{new_time.jd1}, {new_time.jd2}")
>       assert dmap.date == new_time
E       AssertionError: assert <Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340> == <Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>
E         +<Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>
E         -<Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>

../../.tox/py38-32bit/lib/python3.8/site-packages/sunpy/physics/tests/test_differential_rotation.py:244: AssertionError
-------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------
WARNING  sunpy:test_differential_rotation.py:242 2455608.0, -0.24999606481481476
WARNING  sunpy:test_differential_rotation.py:243 2455608.0, -0.24999606481481465
```

2020-10-11 22:07 UTC, nabobalis commented on tox.ini
> +    # allow logging in tests.
```suggestion
    # xdist uses stdout in order to work, we bypass this to allow logging in tests.
```

2020-10-12 09:13 UTC, dstansby commented
Can you check what the `date-obs` value is in the input and output map metadata? I suspect the error might be something to do with how we save the date in the new map at https://github.com/sunpy/sunpy/blob/56e1ab0c2c992f99e0fe3e6bff468b731a51228c/sunpy/physics/differential_rotation.py#L594

2020-10-12 09:30 UTC, nabobalis commented
> Can you check what the `date-obs` value is in the input and output map metadata? I suspect the error might be something to do with how we save the date in the new map at
> 
> https://github.com/sunpy/sunpy/blob/56e1ab0c2c992f99e0fe3e6bff468b731a51228c/sunpy/physics/differential_rotation.py#L594

Locally I get this:
```python
[gw0] PASSED sunpy/physics/tests/test_differential_rotation.py::test_differential_rotate_observer_all_off_disk 
sunpy/physics/tests/test_differential_rotation.py::test_differential_rotate_observer_full_disk WARNING: 2011-02-15T00:00:00.34, 2011-02-15T06:00:00.340 [sunpy.physics.tests.test_differential_rotation]
WARNING: 2455608.0, -0.24999606481481473 [sunpy.physics.tests.test_differential_rotation]
WARNING: 2455608.0, -0.24999606481481473 [sunpy.physics.tests.test_differential_rotation]

[gw0] PASSED sunpy/physics/tests/test_differential_rotation.py::test_differential_rotate_observer_full_disk 
sunpy/physics/tests/test_differential_rotation.py::test_differential_rotate_observer_all_on_disk 
[gw0] PASSED sunpy/physics/tests/test_differential_rotation.py::test_differential_rotate_observer_all_on_disk 
sunpy/physics/tests/test_differential_rotation.py::test_differential_rotate_observer_straddles_limb 
[gw0] PASSED sunpy/physics/tests/test_differential_rotation.py::test_differential_rotate_observer_straddles_limb 
sunpy/physics/tests/test_differential_rotation.py::test_differential_rotate_time_full_disk WARNING: 2011-02-15T00:00:00.34, 2011-02-15T06:00:00.340 [sunpy.physics.tests.test_differential_rotation]
WARNING: 2455608.0, -0.24999606481481473 [sunpy.physics.tests.test_differential_rotation]
```
I will see what the CI gives us.

2020-10-12 11:36 UTC, nabobalis commented
```python
===================================================================================== FAILURES =====================================================================================
___________________________________________________________________ test_differential_rotate_observer_full_disk ____________________________________________________________________
[gw3] linux -- Python 3.8.6 /project/.tox/py38-32bit/bin/python

aia171_test_map = <sunpy.map.sources.sdo.AIAMap object at 0xe5f0e3b8>
SunPy Map
---------
Observatory:		 SDO
Instrument:		 AIA 3
Detecto...0.  ],
       [-0.25,  0.  , -0.5 , ...,  0.75, -0.75,  0.  ],
       [ 0.75,  1.5 , -0.75, ...,  0.  , -0.5 ,  0.5 ]])

    def test_differential_rotate_observer_full_disk(aia171_test_map):
        # Test a full disk map
        new_observer = get_earth(aia171_test_map.date + 6*u.hr)
        dmap = differential_rotate(aia171_test_map, observer=new_observer)
        assert dmap.data.shape == aia171_test_map.data.shape
        logging.warning(f"{aia171_test_map.meta['date-obs']}, {dmap.meta['date-obs']}")
        logging.warning(f"{dmap.date.jd1}, {dmap.date.jd2}")
        logging.warning(f"{new_observer.obstime.jd1}, {new_observer.obstime.jd2}")
>       assert dmap.date == new_observer.obstime
E       AssertionError: assert <Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340> == <Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>
E         +<Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>
E         -<Time object: scale='utc' format='isot' value=2011-02-15T06:00:00.340>

../../.tox/py38-32bit/lib/python3.8/site-packages/sunpy/physics/tests/test_differential_rotation.py:196: AssertionError
-------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------
WARNING  sunpy:test_differential_rotation.py:193 2011-02-15T00:00:00.34, 2011-02-15T06:00:00.340
WARNING  sunpy:test_differential_rotation.py:194 2455608.0, -0.24999606481481476
WARNING  sunpy:test_differential_rotation.py:195 2455608.0, -0.24999606481481465
_____________________________________________________________________ test_differential_rotate_time_full_disk ______________________________________________________________________
[gw3] linux -- Python 3.8.6 /project/.tox/py38-32bit/bin/python
```

2020-10-12 12:26 UTC, dstansby commented
I had a dive into the FITS standard, and both` 011-02-15T00:00:00.34` and `2011-02-15T06:00:00.340` are valid times. I think the 'correct' fix here would be to change
https://github.com/sunpy/sunpy/blob/56e1ab0c2c992f99e0fe3e6bff468b731a51228c/sunpy/physics/differential_rotation.py#L594
to `.obstime.isot`, and therefore we are relying on astropy to create the correct string (instead of using a custom format string).

2020-10-12 12:30 UTC, nabobalis commented
> I had a dive into the FITS standard, and both` 2011-02-15T00:00:00.34` and `2011-02-15T06:00:00.340` are valid times. I think the 'correct' fix here would be to change
> https://github.com/sunpy/sunpy/blob/56e1ab0c2c992f99e0fe3e6bff468b731a51228c/sunpy/physics/differential_rotation.py#L594
> 
> 
> to `.obstime.isot`, and therefore we are relying on astropy to create the correct string (instead of using a custom format string).

I'll do so now.

2020-10-12 12:55 UTC, nabobalis commented
Didn't seem to work.

2020-10-12 13:03 UTC, dstansby commented
Booooo

2020-10-12 13:15 UTC, nabobalis commented
I think the change should be done regardless than a custom string format. But at this point, other than changing the tests I have no ideas.

2020-10-13 13:30 UTC, dstansby commented
I continue to be confused, as there's no obvious reason why the dates shouldn't be exactly the same, going to do some more debugging at https://github.com/sunpy/sunpy/pull/4568

2020-10-13 14:19 UTC, dstansby commented
I got bored, I think this is a tiny floating point error in round tripping strings and the floating point times, I think comparing the isot strings in the test is fine.

2020-10-13 14:29 UTC, nabobalis commented
Will do.

2020-10-14 10:23 UTC, Cadair commented
astropy/astropy#10646 would probably be useful here in the future.

2020-10-17 09:29 UTC, nabobalis commented
Some of the dev figures have changed. I can change the hash but they look worse now?

2020-10-17 10:10 UTC, dstansby approved these changes

2020-10-17 10:16 UTC, dstansby commented
This fixes at least some CI so I'll merge, and take a look at the figure test fails.

2020-10-17 10:36 UTC, merged