Update sun.py to use GeocentricTrueEcliptic
sunpy/sunpy pull request #4584
Opened 2020-10-18 13:26 UTC by kathivashkiv

GeocentricMeanEcliptic coordinates were replaced by GeocentricTrueEcliptic
coordinates in apparent_longitude() and apparent_latitude() functions
due to changes in Astropy4.0
(#4000 issue)

Function `apparent_latitude()` contains explicit adding of nutation:
https://github.com/sunpy/sunpy/blob/master/sunpy/coordinates/sun.py#L202, 
which to some extent repeats the change added to the transformation functions for getting to/from ecliptic systems in https://github.com/astropy/astropy/pull/10129
(https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/ecliptic_transforms.py#L44)

Therefore this correction in `apparent_latitude()' was removed (after this removal all existing in `coordinates` module tests pass).
Can you review this calculation change please?

2020-10-18 13:35 UTC, kakirastern commented
@kathivashkiv You can ignore the coverage tests for now. No need to worry about these.

2020-10-18 13:35 UTC, kakirastern commented
Great work, BTW

2020-10-18 13:36 UTC, kakirastern commented
When the PR is ready for a review please do let us know by pinging either here or on the IRC (Element.io) channel

2020-10-18 13:52 UTC, kathivashkiv commented
> When the PR is ready for a review please do let us know by pinging either here or on the IRC (Element.io) channel

OK) Tell me please who can I ping in such cases?

2020-10-18 13:53 UTC, kakirastern commented
Comme moi or like @Cadair @nabobalis or @ayshih

2020-10-18 13:54 UTC, kakirastern commented
I will assign you someone to review a PR then if no one is on call/duty

2020-10-19 01:39 UTC, ayshih requested changes
Please add a changelog entry, categorized under `trivial`

2020-10-19 01:39 UTC, ayshih commented on sunpy/coordinates/sun.py
> +    GeocentricTrueEcliptic,
```suggestion
    GeocentricTrueEcliptic,
    HeliocentricMeanEcliptic,
```

2020-10-19 01:39 UTC, ayshih commented on sunpy/coordinates/sun.py
>      # Astropy's GeocentricMeanEcliptic already includes aberration, so only add nutation
```suggestion
```

2020-10-19 01:39 UTC, ayshih commented on sunpy/coordinates/sun.py
> +    # change to "Astropy's GeocentricTrueEcliptic already includes both aberration and nutation"?
```suggestion
    # Astropy's GeocentricTrueEcliptic includes both aberration and nutation
```

2020-10-19 01:39 UTC, ayshih commented on sunpy/coordinates/sun.py
> +    # change to "Astropy's GeocentricTrueEcliptic already includes both aberration and nutation"?
```suggestion
    # Astropy's GeocentricTrueEcliptic includes both aberration and nutation
```

2020-10-19 13:20 UTC, ayshih requested changes
I edited the changelog entry, but otherwise this should be good

2020-10-19 13:20 UTC, ayshih commented on changelog/4584.trivial.rst
> +`~sunpy.coordinates.sun.apparent_longitude()` and `~sunpy.coordinates.sun.apparent_latitude()` functions will now use `~astropy.coordinates.GeocentricTrueEcliptic` coordinates
```suggestion
`sunpy.sun` functions now make use of the `~astropy.coordinates.GeocentricTrueEcliptic` frame to simplify internal calculations, but the returned values are unchanged.
```

2020-10-19 15:19 UTC, dstansby approved these changes

2020-10-19 15:53 UTC, ayshih approved these changes
Test failures are unrelated.

2020-10-19 15:54 UTC, merged

2020-10-19 15:54 UTC, ayshih commented
Squashed via GitHub.  Thanks for the PR!