Allow time span with steps to get_horizons_coord
sunpy/sunpy pull request #4698
Opened 2020-12-02 12:37 UTC by dstansby

Fixes https://github.com/sunpy/sunpy/issues/4693; this is currently a draft. Still need to

- [ ] Extract the times from the query
- [ ] Add tests
- [ ] Add a docstring example

2020-12-02 12:37 UTC, pep8speaks commented
Hello @dstansby! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`sunpy/coordinates/ephemeris.py`](https://github.com/sunpy/sunpy/blob/66c1f91705d7512d8da51b8bcc02808ced5b5072/sunpy/coordinates/ephemeris.py):

> [Line 311:101](https://github.com/sunpy/sunpy/blob/66c1f91705d7512d8da51b8bcc02808ced5b5072/sunpy/coordinates/ephemeris.py#L311): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 100 characters)

2021-02-07 09:32 UTC, dstansby commented on sunpy/coordinates/ephemeris.py
> +        {{'start':’YYYY-MM-DD [HH:MM:SS]’, 'stop':’YYYY-MM-DD [HH:MM:SS]’, 'step':’n[y|d|m|s]’}}.
Just coming back to this now, and thought that instead argument could be a list of `[Time, Time, int]` which we internally convert to the jplhorizons string format. Any thoughts @ayshih?

2021-04-13 13:13 UTC, dstansby commented
In case anyone is wondering, the blocker at the moment is the test I have added failing. I haven't looked into it in detail, but at a first (naïve) glance I think it should be passing, so further investigation is needed.

2021-04-13 13:40 UTC, ayshih requested changes
You aren't properly converting to/from TDB.  This fixes the test.

2021-04-13 13:40 UTC, ayshih commented on sunpy/coordinates/ephemeris.py
> +        epochs['stop'] = parse_time(epochs['stop']).strftime(jpl_fmt)
```suggestion
        epochs['start'] = parse_time(epochs['start']).tdb.strftime(jpl_fmt)
        epochs['stop'] = parse_time(epochs['stop']).tdb.strftime(jpl_fmt)
```

2021-04-13 13:40 UTC, ayshih commented on sunpy/coordinates/ephemeris.py
> +        obstime = parse_time(result['datetime_jd'], format='jd')
```suggestion
        obstime = parse_time(result['datetime_jd'], format='jd', scale='tdb')
```

2021-04-13 13:40 UTC, ayshih commented on sunpy/coordinates/tests/test_ephemeris.py
> +    assert_quantity_allclose(e.lon, e_ref.lon)
```suggestion
    assert_quantity_allclose(e.lon, e_ref.lon, atol=1e-9*u.deg)
```

2021-04-13 15:07 UTC, ayshih reviewed
Can you also add a note to the docstring that makes it clear that any times that are provided as strings are interpreted as UTC time (because of `parse_time()`) as opposed to TDB time (which a user of `astroquery` might expect).

2021-04-13 15:07 UTC, ayshih commented on sunpy/coordinates/ephemeris.py
> +                                  'step': '12'}})
```suggestion
    ...                    time={{'start': '2020-12-01',
    ...                           'stop': '2020-12-02',
    ...                           'step': '12'}})
```

2021-04-20 20:05 UTC, ayshih commented on sunpy/coordinates/ephemeris.py
> +    ...                           'step': '12'}})
```suggestion
    ...                           'step': '12'}})  # doctest: +REMOTE_DATA
```

2021-04-28 02:34 UTC, ayshih approved these changes
Small stuff, otherwise looks good

2021-04-28 02:34 UTC, ayshih commented on changelog/4698.feature.rst
> +`sunpy.coordinates.get_horizons_coord` can now be given a start time, end time,
```suggestion
:func:`sunpy.coordinates.get_horizons_coord` can now be given a start time, end time,
```

2021-04-28 02:34 UTC, ayshih commented on sunpy/coordinates/ephemeris.py
> +        and are intepreted as UTC time. ``step`` must be a string with either a
```suggestion
        and are interpreted as UTC time. ``step`` must be a string with either a
```

2021-04-28 14:11 UTC, ayshih commented on sunpy/coordinates/ephemeris.py
> +    >>> get_horizons_coord('Solar Orbiter',
```suggestion
    Query the location of Solar Orbiter at a set of 12 regularly sampled times

    >>> get_horizons_coord('Solar Orbiter',
```

2021-04-28 14:12 UTC, ayshih commented on sunpy/coordinates/ephemeris.py
> +    >>> get_horizons_coord('Solar Orbiter',
(The example isn't rendering properly in the docs)

2021-04-28 15:42 UTC, ayshih approved these changes

2021-04-28 16:25 UTC, nabobalis approved these changes

2021-04-28 16:35 UTC, merged