Change default format of carrington_rotation_time return
sunpy/sunpy pull request #4819
Opened 2021-01-04 16:02 UTC by dstansby

Fixes https://github.com/sunpy/sunpy/issues/4818 - I wasn't sure how to change the scale too here as https://github.com/sunpy/sunpy/issues/4818#issuecomment-754057830 suggests, but happy to with some pointers.

2021-01-04 16:09 UTC, ayshih requested changes

2021-01-04 16:09 UTC, ayshih commented on changelog/4819.trivial.rst
> +Change the format of the time returned from `~sunpy.coordinates.sun.carrington_rotation_number`
```suggestion
Change the format of the time returned from :func:`~sunpy.coordinates.sun.carrington_rotation_number`
```

2021-01-04 16:09 UTC, ayshih commented on sunpy/coordinates/sun.py
> +    t = Time(estimate, scale='tt', format='jd')
```suggestion
    t = Time(estimate, scale='tt', format='jd').utc
```

2021-01-04 16:09 UTC, ayshih commented on sunpy/coordinates/tests/test_sun.py
> +    assert str(t) == '2018-10-26 20:49:25.321'
```suggestion
    assert str(t) == '2018-10-26 20:48:16.137'
```

2021-01-05 14:22 UTC, Cadair commented
Is the scale change here actually more of a change? This will now display different numbers for someone who prints it in `iso` format than before?

2021-01-06 17:09 UTC, nabobalis commented
Is it worth backporting to 2.0?

2021-01-06 17:23 UTC, dstansby commented
I'd say no, since it's not a trivial change.

2021-01-06 17:37 UTC, nabobalis approved these changes

2021-01-06 18:01 UTC, Cadair commented on changelog/4819.trivial.rst
> +Change the format of the time returned from :func:`~sunpy.coordinates.sun.carrington_rotation_number`
This should mention the scale change as well. (Maybe not trivial?)

2021-01-13 10:58 UTC, dstansby commented
I put a changelog in `breaking` just to be safe

2021-01-13 11:25 UTC, Cadair approved these changes

2021-01-21 03:39 UTC, ayshih approved these changes

2021-01-21 03:40 UTC, merged