Add STEREO EUVI colormaps
sunpy/sunpy pull request #4822
Opened 2021-01-04 17:57 UTC by hayesla

### Description
I've been playing around with some EUVI data today so added these colortables for STEREO EUVI. 

There's a weird thing for the 171 channel such that the rgb value arrays arent 256 in size (maybe I'm missing something?), so I've just kept it as `sohoeit171`

Fixes #3702

2021-01-04 17:57 UTC, pep8speaks commented
Hello @hayesla! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`sunpy/visualization/colormaps/color_tables.py`](https://github.com/sunpy/sunpy/blob/ec4f9c8c0a88585697e681f514861fbfd3d8e343/sunpy/visualization/colormaps/color_tables.py):

> [Line 309:1](https://github.com/sunpy/sunpy/blob/ec4f9c8c0a88585697e681f514861fbfd3d8e343/sunpy/visualization/colormaps/color_tables.py#L309): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-01-04 19:42 UTC, dstansby commented
Did you try to add the size != 256 data? Off the top of my head it should work fine, so would be interested in the error if it didn't work.

2021-01-04 19:53 UTC, hayesla commented
> Did you try to add the size != 256 data? Off the top of my head it should work fine, so would be interested in the error if it didn't work.

Oh actually I see where the problem was when I tried (https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/colormaps/color_tables.py#L342 should be `r` rather than `r0`, so is actually working now I think

2021-01-04 20:26 UTC, hayesla commented
Here's an example of the outputs ![euvi_example](https://user-images.githubusercontent.com/4620298/103576373-f377b100-4eca-11eb-8d1a-d53832f5ef4d.png)

2021-01-04 21:32 UTC, dstansby requested changes
Nice, thanks for catching that bug too! I think the only thing left to do is update the figure test hash files, and add a changelog.

2021-01-06 17:24 UTC, dstansby approved these changes
👍 if CI passes

2021-01-28 23:49 UTC, nabobalis commented on changelog/4822.feature.rst
> +Added the STEREO EUVI instrument specific colormaps.
```suggestion
Added the STEREO EUVI instrument specific colormaps called" 'euvi171', 'euvi195', 'euvi284', 'euvi304'. 
```

2021-01-28 23:49 UTC, nabobalis approved these changes

2021-01-28 23:49 UTC, nabobalis commented
Can we get this rebased to solve the merge conflict?

2021-01-29 09:57 UTC, Cadair approved these changes

2021-01-29 10:41 UTC, merged