changed tests for draw_rectangle where tests were repeated
sunpy/sunpy pull request #4830
Opened 2021-01-06 22:43 UTC by jeffreypaul15

### Description

Changed tests for draw_rectangle where the top_right coordinate was specified instead of using width and height ( removed repeated tests ).

2021-01-06 22:43 UTC, pep8speaks commented
Hello @jeffreypaul15! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`sunpy/map/tests/test_plotting.py`](https://github.com/sunpy/sunpy/blob/b13dca7874132d9732111bf38fced175c0c70d63/sunpy/map/tests/test_plotting.py):

> [Line 196:36](https://github.com/sunpy/sunpy/blob/b13dca7874132d9732111bf38fced175c0c70d63/sunpy/map/tests/test_plotting.py#L196): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2021-01-07 04:18 UTC, ayshih requested changes
I like removing the calls to `get_rectangle_coordinates()`.

* If you keep the same rectangle sizes, you shouldn't even need to update the figure hashes.
* The changelog entry is not needed for such an internal change, so remove it.
* Remove the import of `get_rectangle_coordinates` at the beginning of the file.

2021-01-07 04:18 UTC, ayshih commented on sunpy/map/tests/test_plotting.py
> +        200 * u.arcsec, 500 * u.arcsec, frame=aia171_test_map.coordinate_frame)
```suggestion
        100 * u.arcsec, 100 * u.arcsec, frame=aia171_test_map.coordinate_frame)
```

2021-01-07 04:18 UTC, ayshih commented on sunpy/map/tests/test_plotting.py
> +    top_right = SkyCoord(80 * u.deg, 90 * u.deg, frame=hmap.coordinate_frame)
```suggestion
    top_right = SkyCoord(73 * u.deg, 63 * u.deg, frame=heliographic_test_map.coordinate_frame)
```

2021-01-08 04:27 UTC, ayshih approved these changes
Looks good to me, squash when merging

2021-01-08 08:34 UTC, nabobalis approved these changes

2021-01-08 08:34 UTC, merged