Improve differential rotation documentation
sunpy/sunpy pull request #4876
Opened 2021-01-15 22:41 UTC by dstansby

- Add a listing of the different models to the `Notes` section.
- Reference this from the `RotatedSunFrame` docs.
- Remove the link to the IDL equivalent, as I think the rest of the docstring is sufficient to explain the function (unless anyone feels like this should stay?)

2021-01-16 23:22 UTC, ayshih reviewed
Can you also tweak the code examples in the `diff_rot()` docstring so that each actually shows output instead of just assigning it to a variable?

2021-01-16 23:22 UTC, ayshih commented on sunpy/coordinates/metaframes.py
> +        See the documentation for `~sunpy.physics.differential_rotation.diff_rot` for differences
```suggestion
        See the documentation for :func:`~sunpy.physics.differential_rotation.diff_rot` for differences
```

2021-01-16 23:22 UTC, ayshih commented on sunpy/physics/differential_rotation.py
> +    The rotation rate is given by
```suggestion
    The rotation rate at heliographic latitude :math:`\theta` is given by
```

2021-01-16 23:22 UTC, ayshih commented on sunpy/physics/differential_rotation.py
> +    1 mirorad/s is approximately 4.95 deg/day.
```suggestion
    1 microrad/s is approximately 4.95 deg/day.
```

2021-01-19 17:38 UTC, pep8speaks commented
Hello @dstansby! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`sunpy/coordinates/metaframes.py`](https://github.com/sunpy/sunpy/blob/fc8b98759fd8be6ca4bdc36d8163adb6d0c4f0b7/sunpy/coordinates/metaframes.py):

> [Line 151:101](https://github.com/sunpy/sunpy/blob/fc8b98759fd8be6ca4bdc36d8163adb6d0c4f0b7/sunpy/coordinates/metaframes.py#L151): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 100 characters)

2021-01-19 19:02 UTC, ayshih approved these changes
Minor fix for line length, and might as well add a `docfix` changelog entry

2021-01-20 22:53 UTC, wafels commented
I don't have a problem removing the reference to the IDL code as this is a hangover from the early days of SunPy.  The better references are the papers.  Explicitly writing out the function used in these references is also an improvement.

2021-01-28 23:42 UTC, nabobalis requested changes
Changelog just missing.

2021-01-30 14:46 UTC, nabobalis approved these changes

2021-01-30 14:46 UTC, merged