Added an alternate histogram and colormap shading to Map quicklook
sunpy/sunpy pull request #4931
Opened 2021-01-30 04:24 UTC by ayshih

Closes #4864

Map `quicklook()`'s histogram of pixel values has been enhanced with shading to correspond to the colormap.  For many maps, this is not exceptionally useful since the colormap is not distributed well across a linear scale of pixel values.  I've also added a secondary histogram – switch to it by clicking on the histogram – that uses a symmetric-log scale for the pixel values.

For our stock EIT 195 image:
![1](https://user-images.githubusercontent.com/991759/106346899-5f5df700-6288-11eb-9615-943910441f36.png)

And if you click on the histogram:
![2](https://user-images.githubusercontent.com/991759/106346903-6553d800-6288-11eb-866c-1d8b92ee81e6.png)

2021-01-30 04:24 UTC, pep8speaks commented
Hello @ayshih! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`sunpy/map/mapbase.py`](https://github.com/sunpy/sunpy/blob/80f25c5341066adc8e83ae7488b780af566f53c2/sunpy/map/mapbase.py):

> [Line 362:9](https://github.com/sunpy/sunpy/blob/80f25c5341066adc8e83ae7488b780af566f53c2/sunpy/map/mapbase.py#L362): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2021-01-30 04:46 UTC, ayshih commented
Here's the interactive example from the doc build: https://sunpy--4931.org.readthedocs.build/en/4931/api/sunpy.map.MapSequence.html#sunpy.map.MapSequence.quicklook

2021-02-01 11:23 UTC, dstansby commented
Whilst this looks really neat, I'm a bit worried about feature creep, especially for `quicklook()` which should be a simple non-quantitative way to quickly look at the data. My specific questions would be:

- Is there a good reason why we're not using the default colormap and norm to show the images?
- I would advocate for keeping it simple and choosing only one way to show the histogram. Could we can't use the default norm for the map as the x-axis norm in the histogram? Otherwise I'd say defualting to linear scales is reasonable as the simplest choice, unless we know a-priori that almost all data without a default norm will be better with another scale.

2021-02-01 11:57 UTC, nabobalis commented
Yeah I have to agree, I am worried about quicklook growing out of control (even tho it is very fancy).

2021-02-01 15:52 UTC, ayshih commented
> - Is there a good reason why we're not using the default colormap and norm to show the images?

Yes.  The principle of `quicklook()` (to me) is to quickly evaluate the data file, without trusting that the header values are all correct or SunPy's assumptions are appropriate (cf. MDI files).  That's also the reason for histogram equalization, which reveals structure at all pixel values, unlike a default norm, which can hide issues in the data, particularly if the data doesn't exactly conform with the assumptions behind that norm.

If you want to make a plot with the default colormap and norm, just use `plot()` (or `peek()`).  If that plot looks "off", then call `quicklook()`.

This PR is not scope creep.

2021-02-01 16:34 UTC, dstansby commented
👍 on norm/colormap

What's the purpose of the histogram in quicklook()?

I really like the colormap shading of it, agree that it's not ideal on a linear scale, but think the CDF is a bit weird on a log-scale because visually it looks like there are as many pixels below 10e-2 as between 10e0 and 10e1 in the example above.

2021-02-02 14:57 UTC, hayesla approved these changes
This looks great!

2021-02-03 14:36 UTC, ayshih commented
> What's the purpose of the histogram in quicklook()?

In my mind, the distribution of pixel values is useful for determining normalization limits and/or whether your default choices are appropriate.  Imagine that you normally plot HMI magnetograms clipped to -1500 to 1500; the histogram will show you whether that's inappropriate for the file you actually have.

It can also be useful for checking whether the file conforms to your expectations of already-performed processing.  For example, the EIT image shows a clump of negative-values pixels (presumably due to subtracting dark current from map pixels that are not on the sensor?) and a handful of high-valued pixels (presumably hot pixels on the sensor or cosmic-ray hits).  The histogram thus helps you see that you may want to submap to avoid the corners and/or run a de-spiker.

2021-02-07 09:56 UTC, dstansby commented
Thanks for the explanation. I'm still not sure how to usefully interpret the CDF, since the pixel values on the x-axis are normalised. Is there any way to change the x-axis so that the tick values are the actual data values at those tick points instead of the normalised values?

2021-02-07 13:01 UTC, ayshih commented
The X values in the CDF aren't normalized; they're the actual pixel values.  Maybe I'm misunderstanding your question?

2021-02-07 14:48 UTC, dstansby commented
I mean the x-axis in this plot:
<img width="363" alt="Screenshot 2021-02-07 at 14 47 46" src="https://user-images.githubusercontent.com/6197628/107149990-7a4cfd00-6953-11eb-9b31-622da5308ab1.png">

2021-02-13 10:56 UTC, nabobalis commented on sunpy/map/mapbase.py
> +        # Figure instances in matplotlib<3.1 do not create a canvas by default
```suggestion
        # TODO: Figure instances in matplotlib<3.1 do not create a canvas by default
```

Just so we can change this in future.

2021-02-13 10:59 UTC, nabobalis commented
> I meant the x-axis in this plot:
> <img alt="Screenshot 2021-02-07 at 14 47 46" width="363" src="https://user-images.githubusercontent.com/6197628/107149990-7a4cfd00-6953-11eb-9b31-622da5308ab1.png">
> Are these the actual values? If so great, and I just got confused

The histogram code, `ax.hist(finite_data.ravel(), bins=bins, cumulative=True)` So I would assume those are actual values.

2021-02-14 10:31 UTC, dstansby requested changes
Could the "(linear binning)" and "(equalized binning)" be removed from the x-axis labels on the new histogram? They confused me, and I think they're not needed if the values are just the actual pixel values.

2021-02-15 15:12 UTC, ayshih commented
I don't want to entirely remove the description of the type of binning because it's already important information for any histogram, and it's especially important since it's different between the two histograms.  How about I change the labels to "Pixel value in linear bins" and "Pixel value in equalized bins"?

2021-02-15 15:27 UTC, dstansby commented
👍 that sounds good

2021-02-15 19:34 UTC, ayshih commented
Done

2021-02-15 22:03 UTC, dstansby approved these changes

2021-02-15 22:04 UTC, merged