[2.0] Backport of #5038
sunpy/sunpy pull request #5040
Opened 2021-02-27 20:49 UTC by nabobalis

2021-02-27 20:49 UTC, pep8speaks commented
Hello @nabobalis! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`sunpy/net/helio/parser.py`](https://github.com/sunpy/sunpy/blob/c0c3f60860ba5731767e5b89595d62990e3ffbb6/sunpy/net/helio/parser.py):

> [Line 18:101](https://github.com/sunpy/sunpy/blob/c0c3f60860ba5731767e5b89595d62990e3ffbb6/sunpy/net/helio/parser.py#L18): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 100 characters)
> [Line 19:101](https://github.com/sunpy/sunpy/blob/c0c3f60860ba5731767e5b89595d62990e3ffbb6/sunpy/net/helio/parser.py#L19): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 100 characters)
> [Line 27:101](https://github.com/sunpy/sunpy/blob/c0c3f60860ba5731767e5b89595d62990e3ffbb6/sunpy/net/helio/parser.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 100 characters)

2021-02-27 23:26 UTC, nabobalis commented
I need to fix some tests

2021-02-28 15:29 UTC, dstansby requested changes
I don't think we should be merging or releasing workflows (readthedocs) in this case that rely on git branches instead of released packages.

2021-03-01 09:56 UTC, Cadair commented on tox.ini
> +
We don't technically need this here as the tox build runs with `-W` so the behaviour is unchanged with or without the branch.

2021-03-01 10:00 UTC, Cadair commented
> I don't think we should be merging or releasing workflows (readthedocs in this case) that rely on git branches instead of released packages.

We are already using this on the 2.1 and master branches to prevent issues on RTD for PR previews and the actual release build following [a conversation in #sunpy-development:openastronomy.org](https://matrix.to/#/!JYqfIVJjWANcHnfktY:cadair.com/$16133960461201mMqai:cadair.com?via=cadair.com&via=matrix.org). 

I am mostly indifferent to if we backport it or not, but I just thought I would explain the backstory.

2021-03-01 20:47 UTC, nabobalis commented
Since the PR has been merged, I have updated it to point to upstream sphinx gallery.

2021-03-01 23:21 UTC, Cadair approved these changes

2021-03-03 22:33 UTC, merged