revamp color_tables
sunpy/sunpy pull request #5053
Opened 2021-03-03 20:31 UTC by nabobalis

Fixes https://github.com/sunpy/sunpy/issues/5052

2021-03-03 22:03 UTC, dstansby requested changes
Seems a bit overkill (especially for backporting) when the fix could just be a a copy statement when creating `solohri_lya1216`?

2021-03-03 22:06 UTC, nabobalis commented
I think its the right amount of kill. 

We have too many globals floating around and it's caught us here and it should never happen again.

2021-03-03 22:06 UTC, nabobalis commented
Figure tests need updating since the colourtable figure had the bug in it.

2021-03-04 09:34 UTC, Cadair commented
Do we not want to do this on master? I do not like having the globals around even if they are not writeable.

2021-03-04 09:56 UTC, nabobalis commented on sunpy/visualization/colormaps/color_tables.py
> -def cmap_from_rgb_file(name, fname):
I moved this first just because they get called by other functions and I can't handle them being at the end of the file.

2021-03-04 09:56 UTC, nabobalis commented
I've removed the backport and rebased this.

2021-03-06 21:31 UTC, dstansby approved these changes

2021-03-06 21:58 UTC, merged