revert to add_artist for draw_limb to fix bug
sunpy/sunpy pull request #5069
Opened 2021-03-10 19:17 UTC by nabobalis

2021-03-11 09:33 UTC, nabobalis commented
The example is back: https://sunpy--5069.org.readthedocs.build/en/5069/generated/gallery/units_and_coordinates/venus_transit.html#sphx-glr-generated-gallery-units-and-coordinates-venus-transit-py

2021-03-11 15:07 UTC, Cadair approved these changes
Fine with me, would like to know what @dstansby has to say as he understands mpl better than I.

2021-03-11 15:28 UTC, ayshih commented
Copying over my understanding from Element:
> #5019 (backported to 2.1.1 and 2.0.8) changed the limb (which is a Matplotlib patch) so that it is added through add_patch() instead of add_artist(). The plot_coord() call triggers Matplotlib to change the plot limits to include the entire limb because it now realizes that it is there.

> That change to draw_limb() can be reverted on all branches. We ought to use add_patch() for patches that are intended to be in a legend, but it might be okay if we assume that the limb doesn't need to be in a legend...

Presumably `plot_coord()` triggers Matplotlib to change the FOV to include all fully registered patches (ones added through `add_patch()`), but doesn't take into account patches that aren't fully registered (ones added through `add_artist()` instead).

2021-03-11 17:49 UTC, dstansby commented
I've opened an upstream issue here: https://github.com/matplotlib/matplotlib/issues/19685. This seems 👍 for now, but it doesn't feel like a long term solution to me. Will merge this, and see what MPL folk say on that issue.

2021-03-11 17:50 UTC, dstansby requested changes
👍 , but needs a bugfix changelog (unless the `add_patch()` change hasn't found a way into a release yet)

2021-03-12 20:57 UTC, nabobalis commented
Changelog added.

2021-03-12 22:08 UTC, dstansby approved these changes

2021-03-12 22:09 UTC, dstansby commented
Actually it looks like the doc build fail is real, with
```python
<unknown>:34: WARNING: more than one target found for cross-reference 'draw_limb': sunpy.map.CompositeMap.draw_limb, sunpy.map.GenericMap.draw_limb
```

2021-03-12 22:10 UTC, dstansby commented on changelog/5069.bugfix.rst
> +Reverted change for `.draw_limb` that made it use "add_artist" as it was changing the FOV of the plotted image.
```suggestion
Reverted change for `sunpy.map.GenericMap.draw_limb` that made it use "add_artist" as it was changing the FOV of the plotted image.
```

2021-03-12 23:29 UTC, nabobalis commented
I forgot the tilda! Thanks

2021-03-12 23:30 UTC, nabobalis commented
Another issue came up: 
```
/home/vsts/work/1/s/docs/guide/data_types/timeseries.rst:263: WARNING: Exception occurred in plotting timeseries-2
```

2021-03-13 22:05 UTC, nabobalis commented
> Another issue came up:
> 
> ```
> /home/vsts/work/1/s/docs/guide/data_types/timeseries.rst:263: WARNING: Exception occurred in plotting timeseries-2
> ```

I've fixed this in another PR.

2021-03-13 22:05 UTC, merged