ignore warning created in figure-dev-deps
sunpy/sunpy pull request #5070
Opened 2021-03-10 19:24 UTC by nabobalis

2021-03-10 22:49 UTC, dstansby requested changes
We should work out why this is warning, and try and fix it. As a minimum, ignoring this warning needs to have a link to a sunpy issue so we remember ignoring this doesn't get into a release.

2021-03-10 23:15 UTC, nabobalis commented
It comes from this PR: https://github.com/astropy/astropy/pull/11260/files and astropy themselves ignore it.

2021-03-10 23:42 UTC, dstansby commented
Thanks for the PR link - I think we should look into this further, as we don't want users being spammed with these warnings if they're spurious. I'll try and take a look in the next week or so.

2021-03-11 09:34 UTC, nabobalis commented
True, this warning will most likely be emitted when we use the next version of astropy. 

I don't think that holding back on fixing the CI until we investigate this is worth it. We could open an issue to track this?

2021-03-11 11:15 UTC, dstansby commented
Yeah, sorry if I wasn't clear earlier, I'm fine with opening an issue and merging this 👍

2021-03-11 14:45 UTC, Cadair commented
This warning is most likely emitted from WCSLIB so I don't expect there to be a quick fix. Someone should track this down to a MWE, but in a new issue.

2021-03-11 14:45 UTC, Cadair approved these changes

2021-03-11 15:08 UTC, Cadair commented on setup.cfg
> +    # Recent change to astropy has made our figure tests emit this warning.
```suggestion
    # Recent change to astropy has made our figure tests emit this warning.
    # https://github.com/sunpy/sunpy/issues/5073
```

2021-03-12 12:11 UTC, merged