Update self test
sunpy/sunpy pull request #5351
Opened 2021-05-15 10:29 UTC by nabobalis

Added back the self test text removed from #4586
Fixes #3284 (tho the work was in another PR)

2021-05-15 10:33 UTC, nabobalis commented on sunpy/tests/self_test.py
> +        print("If are using conda, you will want to run `conda install <package name>`")
In theory this should not happen with the conda recipe but just in case.

2021-05-21 13:57 UTC, nabobalis commented
I am not backporting this to 3.0, this can go live in 3.1.

2021-06-02 16:31 UTC, Cadair commented on docs/guide/installation.rst
> +This should not appear under a conda install of sunpy but can under a pip install of sunpy.
This is a little misleading. This talking about tests, but at the same time showing optional deps. It's actually quite likely that you will run into not having the tests deps installed.

2021-06-02 17:50 UTC, wtbarnes requested changes
Wording nitpicks

2021-06-02 17:50 UTC, wtbarnes commented on docs/guide/installation.rst
> +The tests will run and will report any fails which you can report at the `sunpy issue tracker <https://github.com/sunpy/sunpy/issues>`__ and we will strive to help.
```suggestion
The tests will run and will report any fails.  You can report these through the `sunpy issue tracker <https://github.com/sunpy/sunpy/issues>`__ and we will strive to help.
```

2021-06-02 17:50 UTC, wtbarnes commented on docs/guide/installation.rst
> +It is possible to run this command and in a situation where not all packages are installed in order to run the test suite, you will see::
```suggestion
It is possible to run this command in a situation where not all packages are installed. If this is the case, you will see the following when you run the test suite::
```

2021-06-02 17:50 UTC, wtbarnes commented on docs/guide/installation.rst
> +This does not mean sunpy is broken, you will need to install the extra packages to ensure a "complete" installation of sunpy.
```suggestion
This does not mean sunpy is broken, but you will need to install the extra packages to ensure a "complete" installation of sunpy and run the entire test suite.
```

2021-06-02 17:50 UTC, wtbarnes commented on docs/guide/installation.rst
> +sunpy enforces a minimum Python version that you will have to use and currently that is Python 3.7 or higher.
I'm not even sure we need this section? 
```suggestion
sunpy requires Python 3.7 or higher.
```

2021-06-18 15:26 UTC, nabobalis commented
All comments should be addressed now.

2021-06-18 18:56 UTC, wtbarnes approved these changes

2021-06-18 18:59 UTC, merged