Use newer data for stereo examples
sunpy/sunpy pull request #5529
Opened 2021-09-18 15:57 UTC by dstansby

Should fix the doc build

2021-09-18 16:11 UTC, nabobalis commented on examples/units_and_coordinates/AIA_limb_STEREO.py
>  # early 2011 when the STEREO spacecraft were roughly 90 deg separated from the
Will need to update the example text as well to match.

2021-09-20 14:21 UTC, nabobalis approved these changes

2021-09-20 15:03 UTC, dstansby commented
https://sunpy--5529.org.readthedocs.build/en/5529/generated/gallery/index.html#coordinates-times-and-units if anyone wants to check the examples are still fine - I've taken a look and they seem to be to me.

2021-09-20 16:25 UTC, merged

2021-09-20 16:47 UTC, ayshih requested changes
Stuff that ought to be changed in this PR:

- Plotting this new AIA image would greatly benefit from explicitly setting `vmin`.

Stuff that would be nice to also get in, but can be a separate PR:

- `AIA_limb_STEREO.py`
  - The ~dozen lines near at the end to annotate the HPC grid as seen by SDO on the STEREO image don't do anything because that HPC grid doesn't actually intersect with the edges of the plot area, so no ticks, tick labels, or axis labels are shown.  One way to "fix" this is to zoom in so that the plot is no longer full-disk.
- `SDO_to_STEREO_Coordinate_Conversion.py`
  - This example needs some re-thinking.  It's really about submapping the same region on two maps from different observers, and the explicit coordinate conversions are all superfluous (now).
  - I – of course – heartily recommend using `draw_quadrangle()` for the plotting of boxes:
![Figure_4](https://user-images.githubusercontent.com/991759/134041401-3bcbd163-ecce-4831-9169-a2935b24d64e.png)
![Figure_6](https://user-images.githubusercontent.com/991759/134041406-3a910988-d424-4b1d-87cc-44e3e406121f.png)

2021-09-20 16:50 UTC, nabobalis commented
> Oh rats, merged while I was typing this. Okay, I'll start a new PR

I opened https://github.com/sunpy/sunpy/issues/5533 to keep track of your suggestions.