Fix distutils in pyinstaller CI
sunpy/sunpy pull request #5771
Opened 2022-01-01 20:24 UTC by ConorMacBride

### Description
This PR swaps `distutils` for `setuptools` in the hook.

We also need to add the `metadata.version('astropy')` because `astropy.wcs.wcs` is imported by pytest due to the `filterwarnings` config. (Not sure why this worked without it before but this is the only way I can get the package to build.)

Can someone with Azure access trigger a manual run to test this?

2022-01-01 20:42 UTC, nabobalis approved these changes

2022-01-01 22:24 UTC, dstansby approved these changes

2022-01-01 22:24 UTC, dstansby requested changes
Actually I'll put a block on this until the CI has been run. Does pyinstaller stuff only need backporting to 3.1.x (and not 3.0.x)?

2022-01-03 20:03 UTC, nabobalis commented
Can we get a rebase on this please?

2022-01-04 16:49 UTC, nabobalis commented
Running it manually with the cronjobs.

2022-01-04 17:03 UTC, ConorMacBride commented
> Does pyinstaller stuff only need backporting to 3.1.x (and not 3.0.x)?

Yes, only 3.1.x. It is not configured in the 3.0.x branch.

The pyinstaller test has passed: https://dev.azure.com/sunpy/sunpy/_build/results?buildId=22298&view=logs&j=40f38f1b-3d58-5f13-e99e-ce730235d7b9&t=9b209db0-6325-5511-8424-734be81d324c

2022-01-04 17:08 UTC, merged