Adds scale="tai" to GOES/XRS time array so that it can ignore leap seconds
sunpy/sunpy pull request #5915
Opened 2022-02-24 11:40 UTC by hayesla

## PR Description

fixes the fact the the GOES netcdf files define their times ignoring leap seconds 

Fixes #5914 

## PR Checklist

- [ x] I have followed the guidelines in the [Contributing document](https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html)
- [ ] Changes follow the coding style of this project
- [ ] Changes have been formatted and linted
- [ ] Changes pass pytest style unit tests (and `pytest` passes).
- [ ] Changes include any required corresponding changes to the documentation
- [ ] Changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] Changes have a descriptive commit message with a short title
- [x] I have added a `Fixes #XXXX -` or `Closes #XXXX -` comment to auto-close the issue that your PR addresses

Need to run some proper tests, but this seems to fix the issue

2022-02-24 12:04 UTC, dstansby submitted a review, later dismissed
Needs a changelog entry. Maybe a test too? If we currently test loading one of these files just a `assert goes.index[0] == #whatever the value is` would be fine, so we can make sure it is correctly parsed under future changes.

2022-02-24 13:51 UTC, ayshih commented
Setting the scale to TAI should not "ignore" leap seconds; TAI counts every second.  Can you provide an example of the problem?

2022-02-24 14:07 UTC, hayesla commented
hmm it seems to - but I'm still a little confused

see here:


```python

>>> Time("1970-01-01 00:00:00.0") + TimeDelta(1505001601.255, format="sec")
<Time object: scale='utc' format='iso' value=2017-09-09 23:59:32.255>

>>> Time("1970-01-01 00:00:00.0", scale="tai") + TimeDelta(1505001601.255, format="sec")
 <Time object: scale='tai' format='iso' value=2017-09-10 00:00:01.255>

```

2022-02-24 14:41 UTC, ayshih commented
Ah, I understand what you are doing now, and it's a bit of computational trickery.  It empirically works, but the `times` instance has the incorrect scale, and a later line calls `times.datetime` without being explicit about the scale that `times` is in, which causes the leap seconds to seemingly vanish.

The proper way to do what you want should be:
```python
# Perform the time addition in UTime format to ignore leap seconds
times = Time(parse_time(start_time_str).utime + d["time"], format='utime')
```

2022-02-25 10:39 UTC, pep8speaks commented
Hello @hayesla! Thanks for updating this PR. 

* In the file [`sunpy/timeseries/sources/goes.py`](https://github.com/sunpy/sunpy/blob/0faa07e1f4d2ff93455d67550d0b1e75dd5d322e/sunpy/timeseries/sources/goes.py):

> [Line 264:1](https://github.com/sunpy/sunpy/blob/0faa07e1f4d2ff93455d67550d0b1e75dd5d322e/sunpy/timeseries/sources/goes.py#L264): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-02-25 11:01 UTC, hayesla commented
still figuring out a test for this as the test files for the GOES netcdf files that I truncated changed the metadata so it time array starts from the start time of the day

2022-02-25 13:27 UTC, ayshih requested changes
~Blocking this for now, see https://github.com/sunpy/sunpy/issues/5914#issuecomment-1050852291~

2022-02-25 15:21 UTC, hayesla commented
this test requires #5917 to be merged first

2022-03-02 20:52 UTC, ayshih approved these changes
I think it'd be helpful to add some comments lest some well-meaning person in the future try to "simplify" the code.

2022-03-02 20:52 UTC, ayshih commented on sunpy/timeseries/sources/goes.py
> +                times = Time(parse_time(start_time_str).utime + d["time"], format="utime")
```suggestion
                # Perform the time addition in UTime format to ignore leap seconds
                times = Time(parse_time(start_time_str).utime + d["time"], format="utime")
```

2022-03-02 20:52 UTC, ayshih commented on sunpy/timeseries/sources/goes.py
> +                times = Time(parse_time(start_time_str).utime + d["time"], format="utime")
```suggestion
                # Perform the time addition in UTime format to ignore leap seconds
                times = Time(parse_time(start_time_str).utime + d["time"], format="utime")
```

2022-03-02 20:52 UTC, ayshih commented on changelog/5915.bugfix.rst
> +Fix parsing of the GOES/Xrs netcdf files to ignore leap seconds/
```suggestion
Fix parsing of the GOES/XRS netcdf files to ignore leap seconds.
```

2022-03-09 17:36 UTC, nabobalis approved these changes

2022-03-09 17:36 UTC, merged