Speeding up Fermi GBM data parsing for TimeSeries
sunpy/sunpy pull request #5943
Opened 2022-03-08 20:26 UTC by hayesla

## PR Description

This fixes #5942 for which reading in fermi GBM files was taking an age and a half

## PR Checklist

- [ ] I have followed the guidelines in the [Contributing document](https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html)
- [ ] Changes follow the coding style of this project
- [ ] Changes have been formatted and linted
- [ ] Changes pass pytest style unit tests (and `pytest` passes).
- [ ] Changes include any required corresponding changes to the documentation
- [ ] Changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [ ] Changes have a descriptive commit message with a short title
- [ ] I have added a `Fixes #XXXX -` or `Closes #XXXX -` comment to auto-close the issue that your PR addresses

2022-03-08 20:38 UTC, hayesla commented
for context - it now takes ~0.2 and ~2s to read the CSPEC and CTIME files, respectively compared to ~12, 200s beforehand.

2022-03-09 10:08 UTC, dstansby requested changes
Looking at the figure images that have changed (https://75296-2165383-gh.circle-artifacts.com/0/.tmp/py38-figure/figure_test_images/fig_comparison.html) it seems like the data being returned in the 800-2000 keV range is different now? If that's bugfix it should be documented in the changelog; if it's a newly introduced bug it should be fixed 😄

2022-03-09 10:18 UTC, hayesla commented
yes sorry I forgot to mention, I've slightly changed the energy edges used for binning (instead of using np.searchsort) and that's the differences here - but it is what we want. I'll update the changelog now! :)

2022-03-10 21:27 UTC, dstansby approved these changes
Given this fixes existing behaviour, approving. It seems odd to me that we're doing this kind of inaccurate reduction to the data though, instead of just returning what's in the file...

2022-03-11 14:49 UTC, ayshih requested changes
Hmm...  The speed-up is great, but I'm a little uncomfortable with this change being a backported bugfix because it does change the approach to binning the data (which wasn't necessary for the speed-up).  While the prior approach wasn't documented and could be considered nonintuitive, this PR's approach also isn't documented and could also be considered nonintuitive.  At the very least, a note should be added to class's docstring to describe what precisely is being done.

Plus, someone should implement a proper rebinning that splits the data bins, and then the binning approach will change again.

2022-03-11 16:37 UTC, hayesla commented
ok yes, I agree - how about I change this PR to just be a speed up, and then another one that properly deals with the binning?

2022-03-11 18:13 UTC, nabobalis commented
How about we backport a separate PR with just the speed fix and leave the bin changes for 4.0?

2022-03-11 18:23 UTC, nabobalis commented
We can create a seperate changelog for the bin changes and label that breaking for 4.0?

2022-03-17 02:48 UTC, ayshih requested changes
The dosctring for `GBMSummaryTimeSeries` ought to elaborate about the rebinning approach.  The existing statement "Note that the data is re-binned from the original 128..." does not have enough detail to discriminate between the old approach and the new approach.  Given the lack of detail, a user might reasonably assume a rebinning approach that includes splitting bins, which is neither the old or the new approaches.

2022-04-05 05:47 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +    The rebinning method is ...
TODO: FIX THIS

2022-04-13 04:40 UTC, ayshih requested changes
Here are the changes for a speed improvement alone, without modifying the rebinning scheme, so it is safe to backport.  Given that the speed improvement is ~2 orders of magnitude, the changelog entry should probably be `bugfix` instead of `trivial`.

2022-04-13 04:40 UTC, ayshih commented on sunpy/timeseries/sources/fermi_gbm.py
>      ebands = [4, 15, 25, 50, 100, 300, 800, 2000]
```suggestion
    ebands = [4, 15, 25, 50, 100, 300, 800, 2000]
    indices = [np.searchsorted(energy_bins['e_max'], e) for e in ebands]
```

2022-04-13 04:40 UTC, ayshih commented on sunpy/timeseries/sources/fermi_gbm.py
> +        ind_end = np.argmin(np.abs(energy_bins["e_max"]-ebands[i+1]))
```suggestion
    for ind_start, ind_end in zip(indices[:-1], indices[1:]):
```

2022-04-13 04:40 UTC, ayshih commented on sunpy/timeseries/sources/fermi_gbm.py
> +        summed_counts = np.sum(count_data["counts"][:, ind_start:ind_end+1], axis=1)
```suggestion
        summed_counts = np.sum(count_data["counts"][:, ind_start:ind_end], axis=1)
```

2022-04-13 04:40 UTC, ayshih commented on changelog/5943.breaking.rst
> +The bin edge indices for `.GBMSummaryTimeSeries` have changed such that it finds the closest energy bin to chosen energy bands.
```suggestion
```
Delete this file

2022-04-13 04:40 UTC, ayshih commented on sunpy/timeseries/sources/fermi_gbm.py
> +    The rebinning method is ...
```suggestion
    The rebinning method treats the counts in each of the original 128 channels as
    all having the energy of the maximum energy of that channel.  For example, the
    counts in an 13.9--15.1 keV original channel would be accumulated into the
    15--25 keV rebinned channel.
```

2022-04-13 05:08 UTC, ayshih requested changes
Add another `bugfix` changelog entry:
```
Fixed bugs with the rebinning and per-keV normalization for Fermi/GBM summary lightcurves.
```

2022-04-13 05:08 UTC, ayshih commented on sunpy/timeseries/sources/fermi_gbm.py
> +        energy_width = (energy_bins["e_max"][ind_end] - energy_bins["e_min"][ind_start])
```suggestion
        energy_width = (energy_bins["e_max"][ind_end - 1] - energy_bins["e_min"][ind_start])
```

2022-04-13 05:08 UTC, ayshih commented on sunpy/timeseries/sources/fermi_gbm.py
> +    15--25 keV rebinned channel.
```suggestion
    all having the energy of the average energy of that channel.  For example, the
    counts in an 14.5--15.6 keV original channel would all be accumulated into the
    15--25 keV rebinned channel.
```

2022-04-13 05:11 UTC, ayshih commented
It turns out that the per-keV calculation is currently wrong, so since we have to bugfix the lightcurves already, I'm now on board with rolling in the better rebinning at the same time.  Let's backport this

2022-04-13 16:20 UTC, ayshih approved these changes
Tweaks to the changelog entries, otherwise looks good (but, I wrote most of it...)

2022-04-13 16:20 UTC, ayshih commented on changelog/5943.bugfix.1.rst
> +Speed up parsing Fermi/GBM files when binning the count data.
```suggestion
Fixed the unintentionally slow parsing of Fermi/GBM files (`~sunpy.timeseries.sources.GBMSummaryTimeSeries`).
```

2022-04-13 16:20 UTC, ayshih commented on changelog/5943.bugfix.2.rst
> +Fixed bugs with the rebinning and per-keV calculation for Fermi/GBM summary lightcurves.
```suggestion
Fixed bugs with the rebinning and per-keV calculation for Fermi/GBM summary lightcurves (`~sunpy.timeseries.sources.GBMSummaryTimeSeries`).
```

2022-04-13 17:00 UTC, nabobalis commented
Doc fails are examples that all I can see.

2022-04-13 17:00 UTC, merged