Test for timeseries
sunpy/sunpy pull request #5980
Opened 2022-03-21 06:54 UTC by akash5100

## PR Description

Draft

- closes #5864
- need help to make this PR complete

## PR Checklist

- [x] I have followed the guidelines in the [Contributing document](https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html)
- [x] Changes follow the coding style of this project
- [x] Changes have been formatted and linted
- [x] Changes pass pytest style unit tests (and `pytest` passes).
- [ ] Changes include any required corresponding changes to the documentation
- [ ] Changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [ ] Changes have a descriptive commit message with a short title
- [x] I have added a `Fixes #XXXX -` or `Closes #XXXX -` comment to auto-close the issue that your PR addresses

2022-03-21 07:08 UTC, nabobalis commented on sunpy/timeseries/timeseriesbase.py
> +def test_timeseries_array():
This should go into a test file.

2022-03-21 07:21 UTC, akash5100 commented on sunpy/timeseries/timeseriesbase.py
> +def test_timeseries_array():
Sorry, by mistake.

2022-03-21 07:26 UTC, nabobalis commented on sunpy/timeseries/tests/test_timeseriesbase.py
> +    # NEED HELP: instead of `datetime.date(2017, 1, 1)` should I use `datetime.datetime.today()`?
```suggestion
```

2022-03-21 16:18 UTC, dstansby requested changes
It looks like the tests are failing on this. Could you take a look at the test failure, and fix it? If you don't understand, feel free to leave a comment with the error message in the failing test and we can try and help.

2022-03-21 17:18 UTC, akash5100 commented
> It looks like the tests are failing on this. Could you take a look at the test failure, and fix it? If you don't understand, feel free to leave a comment with the error message in the failing test and we can try and help.

The test is failing due to the following error:
```
WARNING: SunpyUserWarning: Unknown units for 0 [sunpy.timeseries.timeseriesbase]
```
and I am not sure where I am wrong, most probably here:
> data = np.array([[date, 1], [date, 2], ])
   ts = sunpy.timeseries.TimeSeries(data)

2022-03-21 18:00 UTC, akash5100 commented
> Ah yes, you will need to add units when making the `TimeSeries`. There's an example showing how at https://docs.sunpy.org/en/stable/api/sunpy.timeseries.GenericTimeSeries.html#sunpy.timeseries.GenericTimeSeries

I tried to add units just like the example (but they are optional )
> header = {}
units = {'intensity': u.W/u.m**2} 

and passed it
> ts = sunpy.timeseries.TimeSeries(data, header, units )

and still same warning.

2022-03-21 18:20 UTC, nabobalis commented
It might be worth debugging that by breakpointing into the class and see what is going on.

2022-03-22 10:19 UTC, akash5100 commented
I created DataFrame with the help of `np.array` and a datetime64 `np.array` whose length is equal, and everything is fine. 
In this test can we use `pd.DataFrame`?

2022-03-29 07:31 UTC, akash5100 commented
- With Dataframe
![Screenshot from 2022-03-29 12-51-42](https://user-images.githubusercontent.com/53405133/160556711-0ca9b9d4-e382-446f-9482-79041f062f4f.png)
- With numpy array
![Screenshot from 2022-03-29 12-51-55](https://user-images.githubusercontent.com/53405133/160556747-831975ae-20b9-43fb-975a-23f309ce6633.png)

The unit label on Y-axis are missing when I use the numpy array, that is the reason the tests are failing. I am searching for a way to create a Dataframe like DS using `np.array`.

2022-04-01 09:34 UTC, akash5100 commented
> That's fine, I would expect the label to not be set for a numpy array.
> 
> If we are planning to test that numpy arrays work as input, we also need to update the documentation for timeseries

I am sorry, this took time more than expected, I am fairly new to pytest and unittest. This PR helped me learn about tests and their uses and why we need them. Thank you for waiting 😄

So, should I include updating documentation in this PR?

2022-04-01 16:33 UTC, nabobalis commented
> > That's fine, I would expect the label to not be set for a numpy array.
> > If we are planning to test that numpy arrays work as input, we also need to update the documentation for timeseries
> 
> I am sorry, this took time more than expected, I am fairly new to pytest and unittest. Do these changes look good? This PR helped me learn about tests and their uses and why we need them. Thank you for waiting 😄

I will look at it shortly.

> So, should I include updating documentation in this PR?

Sure.

2022-04-01 16:38 UTC, akash5100 commented
> Sure.

For the documentation of the time series, Can you tell me which part needs changes? and how?

2022-04-01 16:41 UTC, nabobalis commented
> For the documentation of the time series, Can you tell me which part needs changes? and how?

You need to change https://docs.sunpy.org/en/stable/api/sunpy.timeseries.GenericTimeSeries.html#sunpy.timeseries.GenericTimeSeries to say for the data variable, pd.dataframe or numpy array.

2022-04-01 16:41 UTC, dstansby approved these changes
Thanks - this hits the line that needed covering in the tests 🎉

2022-04-01 16:42 UTC, merged

2022-04-01 16:44 UTC, akash5100 commented
Thank you @dstansby, for the review

> You need to change https://docs.sunpy.org/en/stable/api/sunpy.timeseries.GenericTimeSeries.html#sunpy.timeseries.GenericTimeSeries to say for the data variable, pd.dataframe or numpy array.

Should, I add this in a new PR?

2022-04-01 16:47 UTC, nabobalis commented
> Thank you @dstansby, for the review
> 
> > You need to change [docs.sunpy.org/en/stable/api/sunpy.timeseries.GenericTimeSeries.html#sunpy.timeseries.GenericTimeSeries](https://docs.sunpy.org/en/stable/api/sunpy.timeseries.GenericTimeSeries.html#sunpy.timeseries.GenericTimeSeries) to say for the data variable, pd.dataframe or numpy array.
> 
> Should, I add this in a new PR?

Yes please.