Overrride EUI waveunit
sunpy/sunpy pull request #6217
Opened 2022-06-07 15:47 UTC by dstansby

Fixes https://github.com/sunpy/sunpy/issues/6198 - see https://issues.cosmos.esa.int/solarorbiterwiki/display/SOSP/Metadata+Definition+for+Solar+Orbiter+Science+Data for the ESA documentation that says this should be Angstrom.

I checked loading a .jp2 file with this PR, and it correctly loads the right colormap 🎉

2022-06-07 15:48 UTC, nabobalis commented
Do we need to add back the colormap line?

2022-06-07 15:49 UTC, dstansby commented
> Do we need to add back the colormap line?

No

2022-06-07 15:52 UTC, Cadair requested changes
If this is only an issue with jp2 files and not FITS files this probably isn't the correct solution.

2022-06-07 21:43 UTC, wtbarnes commented on sunpy/map/sources/solo.py
> +        # the metadata spec wavelengths are always in Angstrom
```suggestion
        # EUI JP2000 files do not have the WAVEUNIT key in the metadata.
        # However, the FITS files do.
        # The EUI metadata spec says the WAVELNTH key is always expressed
        # in Angstroms so we assume this if the WAVEUNIT is missing.
```

2022-06-07 21:43 UTC, wtbarnes approved these changes

2022-06-07 21:50 UTC, Cadair approved these changes
Happy with this now it defaults to extracting and falls back to Angstrom

2022-06-07 22:37 UTC, merged

2022-06-08 05:54 UTC, bogdanni commented
If this keyword is added in the next EUI data release, would this representation be OK?
```
WAVEUNIT= 'Angstrom' / Wavelength unit: angstrom
```
Note the capitalization guided by the FITS standard, where 'Angstrom' is the unit and 'angstrom' is the meaning.

2022-06-08 05:54 UTC, bogdanni commented
If this keyword is added in the next EUI data release, would this representation be OK?
```
WAVEUNIT= 'Angstrom' / Wavelength unit: angstrom
```
Note the capitalization guided by the FITS standard, where 'Angstrom' is the unit and 'angstrom' is the meaning.

2022-06-08 06:05 UTC, nabobalis commented
I would have to double check, but I am pretty sure that would work with `extract_waveunit`

2022-06-08 06:38 UTC, Cadair commented
@bogdanni that would work. To be clear though what you have at the moment is perfectly spec compliant and works great for the EUI FITS files, it's just that the JPEG2000 files made by helioviewer (I assume) strip out the FITS comment with the unit in.

2022-06-08 06:54 UTC, bogdanni commented
The Helioviewer XML metadata in JP2 files cannot transcribe the FITS header comments, so this is an explicit solution.