PR cheatsheet for the dev_guide
sunpy/sunpy pull request #6346
Opened 2022-08-01 21:17 UTC by mwhv2

This PR adds a “pull request cheat sheet” to the SunPy Developer’s Guide (address Issue #5944). At the moment, it is grouped with the “Getting started” part of the guide, but I think it could also fit under “Conventions”. Here is a link to the [cheat sheet](https://github.com/mwhv2/sunpy-git/blob/cheatsheet/docs/dev_guide/contents/cheatsheet.rst) on my branch where the formatting is a bit easier to review.

There are seven general steps that the guide highlights, and each step has additional notes that provide more information about that step of the process. I have tried to provide links that either explain how a particular step is done or describe what is being done.

Another possible step to add is deleting the branch after the PR has been merged. Since I am still getting used to Github, I am not sure if this is common/best practice. What are everyone’s thoughts on this?

Let me know if I missed any steps of the process, or if other information should be included.

2022-08-01 22:10 UTC, nabobalis requested changes
Thanks for the PR, it's a very good start.

2022-08-01 22:10 UTC, nabobalis commented on docs/dev_guide/contents/cheatsheet.rst
> +7. Ask questions if you get stuck or confused at any point
```suggestion
#. Ask questions if you get stuck or confused at any point!
```

2022-08-01 22:10 UTC, nabobalis commented on docs/dev_guide/contents/cheatsheet.rst
> +    a. Open-source projects are about communication and collaboration
```suggestion
    #. Open-source projects are about communication and collaboration.
```

2022-08-01 22:10 UTC, nabobalis commented on docs/dev_guide/contents/cheatsheet.rst
> +    b. Join the SunPy Matrix Chat channel (link at the bottom of this page)
```suggestion
    b. `Join the SunPy Matrix Chat channel <https://matrix.to/#/+sunpy:openastronomy.org>`__.
```

2022-08-01 22:10 UTC, nabobalis commented on docs/dev_guide/contents/cheatsheet.rst
> +Making a change to the SunPy website? See `these guidelines <https://github.com/sunpy/sunpy.org#sunpyorg-website>`_ for making website changes.
```suggestion
```
I think this is ok not being there.

2022-08-01 22:10 UTC, nabobalis commented on docs/dev_guide/contents/cheatsheet.rst
> +New to Git/Github? Check out the `Newcomers' Guide <https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html>`_ and `Git Cheat Sheets <https://training.github.com/>`_.
```suggestion
```
I am going to move this to the top.

2022-08-01 22:10 UTC, nabobalis commented on docs/dev_guide/contents/cheatsheet.rst
> +
```suggestion
New to Git and Github?
Check out the :ref:`newcomers` and `Git Cheat Sheets <https://training.github.com/>`__.

If you would prefer a visual Git interface, you can try `Github Desktop <https://desktop.github.com/>`__ or  `GitKraken <https://www.gitkraken.com/>`__.

```

2022-08-01 22:13 UTC, nabobalis commented
> Another possible step to add is deleting the branch after the PR has been merged. Since I am still getting used to Github, I am not sure if this is common/best practice. What are everyone’s thoughts on this?

Always delete the branch when its merged is my stance.

2022-08-02 02:19 UTC, ayshih commented
This guide is looking fairly good, but it isn't really structured like a "cheat sheet", so I wouldn't call it that.

> > Another possible step to add is deleting the branch after the PR has been merged. Since I am still getting used to Github, I am not sure if this is common/best practice. What are everyone’s thoughts on this?
> 
> Always delete the branch when its merged is my stance.

While I'm quite diligent about deleting my own branches and keeping my local repo clean, I don't think you should add such a step to this guide.  The guide is already long enough, and I think that GitHub does a good job of suggesting branch deletion to the user.

2022-08-02 02:53 UTC, nabobalis commented
> While I'm quite diligent about deleting my own branches and keeping my local repo clean, I don't think you should add such a step to this guide. The guide is already long enough, and I think that GitHub does a good job of suggesting branch deletion to the user.

Yeah that's a good point, we should not add it to the guide.

2022-08-02 15:47 UTC, wtbarnes commented
I like the look of this. Re: @ayshih's comment about the name "cheat sheet," would "check list" maybe be a better word? 

I also think we should format this actually as a check list and incorporate a pared-down version of it into the PR template, with a link to the full version in the docs.

2022-08-02 21:13 UTC, mwhv2 commented
As a followup to @wtbarnes check list suggestion, I have edited a [version of the cheatsheet](https://github.com/mwhv2/sunpy-git/blob/test_docs/docs/dev_guide/contents/cheatsheet.rst) (now check list) on another test branch of mine that includes dynamic check boxes. It is accomplished using the “raw” special directive. However, due to the large warning and caution labels in the [documentation](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through), I am not sure if this method is advisable to use. If anyone likes the idea of check boxes, I am open to suggestions of how to implement them.

Otherwise, I think calling it a check list makes more sense.

2022-08-02 21:19 UTC, nabobalis commented
The checklist version would go into a yaml file that would be read by GitHub. It would not be added to our documentation build.

I think it is something we can worry about when we finalise the list.

2022-08-10 17:45 UTC, nabobalis commented on docs/dev_guide/index.rst
> +            contents/cheatsheet
```suggestion
            contents/pr_checklist
```

With the file being renamed too.

2022-08-10 17:53 UTC, nabobalis approved these changes

2022-08-30 19:07 UTC, dstansby approved these changes
This is awesome, thanks a lot for writing it!

2022-08-30 19:07 UTC, merged