Clean up SXTMap and add source tests and test data
sunpy/sunpy pull request #6436
Opened 2022-09-29 19:33 UTC by wtbarnes

## Issues Resolved
Fixes #4395 and #5140.

I think this also fixes #4998 if this is in fact the last instance of assuming an Earth based observer.

## Description

This PR does several things:

- Add test data for Yohkoh SXT
- Add source test for `SXTMap`
- Clean up the `SXTMap` code
- Makes a few changes in `GenericMap` to check `if not ...` rather than `if <key> is None` in the cases where some keywords (e.g. `CTYPE`, `DATE-OBS`) may be present but empty. In these cases, we want the behavior to be the same as if they were missing (i.e. fall back to the default behavior). 

With regard to the last change, if it is preferable to pull out the last change into a separate PR, I'm happy to do that.

With regard to cleaning up the `SXTMap` source, I've removed the fix for `dsun` as I was not able to find an SXT file where this value was missing or incorrectly calculated (i.e. it is approximately 1 AU rather than incorrectly set as the solar diameter as it previously was). As such, there is not need for any manual correction of this value.

2022-09-29 19:52 UTC, wtbarnes commented
I'll also point out that while `HGS_LON` and `HGS_LAT` are both zero, there are additional keys

```
LAT     =              10.9955 / Yoh Orb: Spacecraft Lattitude
LONG    =              315.861 / Yoh Orb: Spacecraft Longitude
HEIGHT  =              777.563 / Yoh Orb: Spacecrft Altitude (Km)
RADIUS  =              7154.83 / Yoh Orb: Radius
```

that seem to refer to some Earth-centered coordinate system. If we can work out what this is and if it is supported by astropy, we could work out whether this is consistent with the value of (0,0) that we're currently using.

2022-09-29 20:52 UTC, wtbarnes commented
I've added support for pulling the observer coordinate information from the (`LAT`,`LONG`,`RADIUS`) keys and assuming they're in the ITRS coordinate system. This gives
```
<SkyCoord (HeliographicStonyhurst: obstime=1991-11-05T11:10:24.018, rsun=695491.3001881952 km): (lon, lat, radius) in (deg, deg, km)
    (0.00235782, 3.95525146, 1.48328342e+08)>
```
which differs substantially from the observer coordinate as derived from the (`HGS_LON`,`HGS_LAT`,`DSUN_OBS`) keys,
```
<SkyCoord (HeliographicStonyhurst: obstime=1991-11-05T10:10:24.025, rsun=695505.9513199404 km): (lon, lat, radius) in (deg, deg, m)
    (0., 0., 1.48333e+11)>
```

I do not know which is more accurate.

2022-09-29 20:57 UTC, wtbarnes commented
If we go ahead with using this approach for computing the observer coordinate, should also confirm what the exact coordinate frame is. Assuming [ITRS](https://www.iers.org/SharedDocs/Publikationen/EN/IERS/Publications/tn/TechnNote36/tn36_031.pdf?__blob=publicationFile&v=1) for now.

2022-09-29 21:38 UTC, ayshih commented
> I do not know which is more accurate.

100% that the `HGLT_OBS` value is very wrong; It is impossible for it to be zero here.  Note that `SOLAR_B0` has a more usable value of 3.9536 for the heliographic latitude.

`ITRS` should be a fairly safe assumption.

2022-09-30 09:53 UTC, dstansby requested changes
Looks like the tests need updating to account for the new coordinate information

2022-09-30 16:28 UTC, wtbarnes commented on changelog/6436.bugfix.2.rst
> +In `~sunpy.map.GenericMap.coordinate_system` and `~sunpy.map.GenericMap._get_date`, the default values
Yes, the change was made in a private method so I'm not exactly sure how to document that in the changelog. The more user-facing behavior is that if any of the date keys (e.g. `DATE-OBS`) are present but empty, they're treated as missing.

2022-09-30 16:33 UTC, wtbarnes commented on changelog/6436.bugfix.2.rst
> +In `~sunpy.map.GenericMap.coordinate_system` and `~sunpy.map.GenericMap._get_date`, the default values
I've clarified the changelog a bit to not reference a private method.

2022-09-30 17:14 UTC, nabobalis approved these changes

2022-09-30 17:14 UTC, merged

2022-10-01 00:48 UTC, ayshih commented
My recommendation is to add a note to the `SXTMap` docstring about which observer information we are trusting, analogous to the one for `SUVIMap`:
https://github.com/sunpy/sunpy/blob/1ee9c6995de8cb1bb269b2f006090e98231a6030/sunpy/map/sources/suvi.py#L51-L55