Optionally preserve metadata in `reproject_to`
sunpy/sunpy pull request #6502
Opened 2022-10-24 18:10 UTC by wtbarnes

Fixes #5627 

This uses the header helper to optionally pass through a subset of the instrument keywords when using `reproject_to` and also ensures that the new map is the same subclass as the old map. As discussed in the above issue, this is not always a correct assumption so this False by default.

I'm not completely sure about the best way to do this. This should also wait on #6499 so that the unit can be easily passed through to the new instance.

## TODOs 

- [ ] Incorporate changes from #6499 
- [ ] Make use of a `telescope` attribute on Map?
- [ ] Tests
- [ ] Changelog

2022-10-27 00:34 UTC, ayshih commented
> the new map is the same subclass as the old map

I recognize the intent, but now that we no longer modify/fix the metadata on instantiation (#5501), I think you'll have to figure out how to support those Map subclasses that construct their properties from non-standard keywords (or from standard keywords in a non-standard way).  Skipping the instantiation was previously possible, but now the subclass properties will need to know whether they ought to be reading the metadata in the source-specific way or in the default way.

2022-10-27 14:19 UTC, wtbarnes commented
Oh good point. I had not even thought about that...

Thinking about it a little more, I think it's fine to just do away with instantiating through the specific subclass and just route the new map creation through `GenericMap`. As long as the needed metadata is accessible (e.g. `wavelength` in David's example in #5627), then that's the only thing that matters. The purpose of the source-specific subclasses is to normalize the representation of the metadata. If we've already done that via the header helper, then there's no need to use the source specific subclass.

2022-10-27 16:09 UTC, Cadair requested changes
this significantly deviates the behaviour of this method away from ndcube which I am not a massive fan of. I need to think about this in more detail.

2022-10-27 18:42 UTC, ayshih commented
Some thoughts:

- The name of the keyword should probably be changed to something less seemingly comprehensive than `preserve_meta`, e.g., `preserve_core_meta` or `preserve_basic_meta`.
- Of the metadata that is being preserved, `unit` gives me pause, as I've mentioned before.
- As @Cadair notes, there continues to be a disparity between the two `reproject_to()` methods.  Amusingly, you would have moved our `reproject_to()` closer to NDCube's had you kept the instantiation of the subclass.

2022-10-27 18:57 UTC, wtbarnes commented
Another option that would address the NDCube API consistency issue: `preserve_meta` would preserve *every* non-WCS keyword (or any keyword that is not included from the new header) from the old header and then instatiate the new map through `_new_instance`.

This makes me a little nervous because there are many extra keywords in headers that then may become stale (e.g. ones related to statistics on the data), but this happens with our other methods like resample, rotate, etc and the properties exposed by `GenericMap` does not depend on them. We would just have to make absolutely sure that there are no stale keywords left around that are used by `GenericMap`

2023-05-08 17:39 UTC, ayshih reviewed
Doesn't your current implementation fail to strip out all WCS keywords from the original map header before merging in WCS keywords from the target header?  It seems like it'd be easy to end up with a output map header that contains inconsistent metadata (e.g., a PCij matrix not matching a CROTA2 value).

2023-05-08 19:34 UTC, wtbarnes commented
I think I've been convinced that this is just not a viable option because of the way we treat our metadata, both in terms of our use of source-specific classes and our decision to not modify the underlying metadata. There is no way to reconcile this with propagating `type(class)` when creating a reprojected map. This works fine in NDCube because of the strict separation between WCS and non-WCS metadata.

2023-05-08 19:34 UTC, closed without merging