Update self_test
sunpy/sunpy pull request #6600
Opened 2022-11-12 00:56 UTC by nabobalis

1. Non-zero return
2. Allow `python -m sunpy.tests.self_test`

2022-11-12 09:21 UTC, Cadair commented on sunpy/tests/self_test.py
> +    self_test(package=test_args.package, online=test_args.online,
This should use sys.exit.

2022-11-13 05:10 UTC, nabobalis commented on sunpy/tests/self_test.py
> +    self_test(package=test_args.package, online=test_args.online,
Fixed.

2022-11-14 10:35 UTC, Cadair approved these changes
My only remaining comment is if it's worth running this as part of our CI?

2022-11-14 10:37 UTC, Cadair requested changes
Ok, so I tested this locally and it dosen't seem to work if you run it outside of the source checkout:

```
python -m "sunpy.tests.self_test"



Starting sunpy self test...
Checking for packages needed to run sunpy:
All required and optional sunpy dependencies are installed.
Starting the sunpy test suite:

==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.10.8, pytest-7.1.1, pluggy-1.0.0
Matplotlib: 3.6.1
Freetype: 2.6.1
rootdir: /home/stuart
plugins: remotedata-0.3.3, openfiles-0.5.0, mock-3.7.0, filter-subpackage-0.1.1, doctestplus-0.12.0, cov-3.0.0, astropy-header-0.2.1, arraydiff-0.5.0, hypothesis-6.39.4, mpl-0.14.0, intercept-remote-1.25, asdf-2.11.0, forked-1.4.0, xdist-2.5.0, napari-plugin-engine-0.2.0, npe2-0.6.1, napari-0.4.16, astropy-0.10.0
collected 0 items                                                                                                                                                                            

=================================================================================== no tests ran in 0.47s ====================================================================================
```

2022-11-15 07:16 UTC, nabobalis commented
Oh I think I know what it is, did you remove the `sunpy` directory from your home directory?

2022-11-17 09:42 UTC, Cadair approved these changes

2022-11-17 09:42 UTC, merged