Change use of world_to_pixel / pixel_to_world to wcs.world_to_pixel / pixel_to_world in the docs.
sunpy/sunpy pull request #6732
Opened 2023-01-26 06:07 UTC by ryuusama09

## PR Description
 fixes wcs in codebase except tests.
supersedes pr : https://github.com/sunpy/sunpy/pull/6723
fixes : https://github.com/sunpy/sunpy/issues/6435

2023-01-26 06:21 UTC, nabobalis commented on CHANGELOG.rst
>    attributes are set on a `~astropy.wcs.WCS`. (`#5348 <https://github.com/sunpy/sunpy/pull/5348>`__)
This file needs to be reset back to normal.

2023-01-26 06:21 UTC, nabobalis commented on docs/intro/coordinates.rst
>     PixelPair(x=<Quantity 551.7680511 pix>, y=<Quantity 515.18266871 pix>)
This output will now be different.

2023-01-26 06:22 UTC, nabobalis commented on docs/intro/coordinates.rst
> +   The `~astropy.coordinates.SkyCoord` object can be converted to a PixelPair object using `~sunpy.map.GenericMap.wcs.world_to_pixel`:
```suggestion
   The `~astropy.coordinates.SkyCoord` object can be converted to a pair of pixels using `~sunpy.map.GenericMap.wcs.world_to_pixel`:
```

2023-01-26 06:23 UTC, nabobalis commented on examples/plotting/hmi_cutout.py
>      (0, 0), (xpix.value, ypix.value), 'axes fraction', 'data', axesA=ax2, axesB=ax1,
This file should fail as far as I can see.

2023-01-26 06:23 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  xlims_pixel = pixel_coords.x.value
This example should also fail if I understand correctly.

2023-01-26 06:25 UTC, nabobalis commented
> @nabobalis , i dont know how the map tests are failing , theyre just working fine locally 😥

When the tests run, I will check the logs.

2023-01-26 06:28 UTC, nabobalis commented
Looks like you need to change:

```
>       xy2 = np.dstack([x2.T.value.flat, y2.T.value.flat])[0]
```
to account for the change in world to pixel output.

2023-01-26 06:29 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  xlims_pixel = pixel_coords.x.value
> ill check on this . also why does changelog needs to be reset. It should show that we have changed to wcs right

That is not how we do that. The file should be changed back to normal.

2023-01-26 06:44 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  xlims_pixel = pixel_coords.x.value
Sure, but now we don't have a pixel pair, you have to change the lines in th example that assume it is a pixel pair.

2023-01-26 06:47 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  xlims_pixel = pixel_coords.x.value
No, but we don't need that. We can change the other lines in the example.

2023-01-26 06:59 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  xlims_pixel = pixel_coords.x.value
We should not be using PixelPair, you need to change the other lines of the example.

The changelog file still has changes.

2023-01-26 07:01 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +        x2, y2 = smap.wcs.world_to_pixel(coordinates_at_map_observer)
Since this has changed, the places where x2 and y2 are used, need to be updated.

2023-01-26 07:02 UTC, nabobalis commented on examples/plotting/xy_lims.py
> +# pixel_coords = PixelPair(pixel_coords_x,pixel_coords_y)
```suggestion
```
You need to update the lines below.

2023-01-27 03:21 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +        x2, y2 = smap.wcs.world_to_pixel(coordinates_at_map_observer)
Something has to be changed to make the code work again. If x2 and y2 here arent, then what should we change?

2023-01-27 03:43 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +        x2, y2 = smap.wcs.world_to_pixel(coordinates_at_map_observer)
world_to_pixel always returns two values. That can either be assigned to one variable or two, like in this case.

We don't need to worry about pixel_to_world

2023-01-27 03:59 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +        x2, y2 = smap.wcs.world_to_pixel(coordinates_at_map_observer)
The changelog has not been reverted.

The fix can not be using pixelpair, we have to change other parts of the code.

2023-01-27 04:00 UTC, nabobalis commented on examples/plotting/xy_lims.py
> +from sunpy.map import PixelPair
We can not use this to fix the example, the answer lies in changing other lines of code.

2023-01-27 04:00 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +from sunpy.map import PixelPair
```suggestion
```

2023-01-27 04:01 UTC, nabobalis commented on examples/plotting/xy_lims.py
> +#pixel_coords = PixelPair(pixel_coords_x,pixel_coords_y)
```suggestion
```

2023-01-27 04:01 UTC, nabobalis commented on examples/plotting/xy_lims.py
> +from sunpy.map import PixelPair
```suggestion
```

2023-01-27 04:01 UTC, nabobalis commented on examples/plotting/hmi_cutout.py
> +#xpix, ypix = magnetogram_big.wcs.world_to_pixel(right_corner)
```suggestion
```

2023-01-27 04:01 UTC, nabobalis commented on examples/plotting/hmi_cutout.py
> +ypix = xypix[1]
```suggestion
xpix, ypix = magnetogram_big.wcs.world_to_pixel(right_corner)
```

2023-01-27 04:02 UTC, nabobalis commented on examples/plotting/hmi_cutout.py
>      (0, 1), (xpix.value, ypix.value), 'axes fraction', 'data', axesA=ax2, axesB=ax1,
```suggestion
    (0, 1), (xpix, ypix), 'axes fraction', 'data', axesA=ax2, axesB=ax1,
```

2023-01-27 04:02 UTC, nabobalis commented on examples/plotting/hmi_cutout.py
> +xypix = magnetogram_big.wcs.world_to_pixel(
```suggestion
xpix, ypix = magnetogram_big.wcs.world_to_pixel(
```

2023-01-27 04:02 UTC, nabobalis commented on examples/plotting/hmi_cutout.py
> +ypix = xypix[1]
```suggestion
```

2023-01-27 04:02 UTC, nabobalis commented on examples/plotting/hmi_cutout.py
>      (0, 0), (xpix.value, ypix.value), 'axes fraction', 'data', axesA=ax2, axesB=ax1,
```suggestion
    (0, 0), (xpix, ypix), 'axes fraction', 'data', axesA=ax2, axesB=ax1,
```

2023-01-27 04:03 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  xlims_pixel = pixel_coords.x.value
```suggestion
```

2023-01-27 04:03 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  xlims_pixel = pixel_coords.x.value
The line below has to go as well.

2023-01-27 04:05 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +        y2 = pix[1]
```suggestion
        x2, y2 = smap.wcs.world_to_pixel(coordinates_at_map_observer)
```

2023-01-27 04:05 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
>      xy2 = np.dstack([x2.T.value.flat, y2.T.value.flat])[0]
```suggestion
    xy2 = np.dstack([x2.T.flat, y2.T.flat])[0]
```

2023-01-27 04:09 UTC, nabobalis commented
> I will revert the changelog. 

Thanks

> But it is necessary to use pixelpair because x2 ,y2 have to be a pixel quantity. To make x2,y2 as a pixel quantity we need pixelpair.

Why do x2 and y2 need to be pixels?

2023-01-27 04:09 UTC, nabobalis commented on examples/plotting/hmi_cutout.py
> +from sunpy.map import PixelPair
```suggestion
```

2023-01-27 04:10 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  import sunpy.map
```suggestion
import sunpy.map

```

2023-01-27 04:10 UTC, nabobalis commented on examples/plotting/xy_lims.py
> +#pixel_coords = PixelPair(pixel_coords_x,pixel_coords_y)
Why do they need to be a pixel pair?

2023-01-27 04:11 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
>  from astropy.time import TimeDelta
```suggestion
from astropy.time import TimeDelta

```

2023-01-27 04:11 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +        map_coord= smap.wcs.pixel_to_world(*input_pixels)
```suggestion
        map_coord = smap.wcs.pixel_to_world(*input_pixels)
```

2023-01-27 04:12 UTC, nabobalis commented
> > Why do x2 and y2 need to be pixels?
> 
> because during tests it mentioned , "numpy.ndarray has not attribute value" . this meant that it has to be a pixel quantity.

Ok, so why do we not change this instead of making them a pixel pair?

2023-01-27 04:16 UTC, nabobalis commented
> @nabobalis , only the `changelog.rst` has to be changed or all files in changelog directory ?

only the files you changed.

2023-01-27 04:20 UTC, nabobalis commented on CHANGELOG.rst
> +      top_right = smap.world_to_pixel(top_right) * u.pix
These should not be here.

2023-01-27 04:21 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +
```suggestion
```

2023-01-27 04:21 UTC, nabobalis commented on sunpy/physics/differential_rotation.py
> +
```suggestion
```

2023-01-27 04:23 UTC, nabobalis commented
> then i think we will have to change the line ` xy2 = np.dstack([x2.T.value.flat, y2.T.value.flat])[0]` to something else.

I think we should do that.

> I personally feel we should keep it as a pixel quantity as it will show how to use `wcs.wtp` to derive a pixel quantity and not a tuple

This code is internal, I don't understand how it would do that.

2023-01-27 04:28 UTC, nabobalis commented on CHANGELOG.rst
> +      top_right = smap.world_to_pixel(top_right) * u.pix
That is there in your code base, the `wcs` is missing.

2023-01-27 04:30 UTC, nabobalis commented
> then i guess it would simply mean `np.dstack(x2,y2)`.

So far the tests are passing with the current version.

2023-01-27 04:30 UTC, nabobalis commented on examples/plotting/xy_lims.py
>  ylims_pixel = pixel_coords.y.value
```suggestion
```

2023-01-27 04:31 UTC, nabobalis commented on examples/plotting/xy_lims.py
> +pixel_coords_x , pixel_coords_y = aia_map.wcs.world_to_pixel(world_coords)
You will need to update the lines below that set the xlim and ylim otherwise this example will error.

2023-01-27 04:34 UTC, nabobalis commented on examples/plotting/xy_lims.py
> +pixel_coords_x , pixel_coords_y = aia_map.wcs.world_to_pixel(world_coords)
That is surprising to me, if that's the case, then that's ok.

2023-01-27 04:42 UTC, nabobalis commented
That looks like everything @ryuusama09.
Thanks for the powering through the longer review process for this issue.

2023-01-27 05:20 UTC, nabobalis commented
> i think we are good to go for merge ? @nabobalis

This will need a review from others first.

2023-01-29 04:33 UTC, nabobalis commented
> @nabobalis , is there any issue over here that it isnt being merged?

No, I have requested a review from another person and we will wait for that before this gets merged.

2023-02-08 22:47 UTC, nabobalis commented
Can you merge in the latest version of sunpy/main?

I want to check all the tests pass.

2023-02-09 16:16 UTC, nabobalis commented
Thanks

2023-02-09 16:20 UTC, nabobalis commented
If you could but I think there is also a genuine issue that needs fixing in that pull request.

2023-02-26 17:57 UTC, nabobalis commented
> @nabobalis , i would like to connect with you on mail regarding the gsoc 2023 projects . If possible could ou share your email ?

Please do not @ people unless it's important. 

All GSoC communications should happen in the main chat room: https://app.element.io/#/room/#sunpy:openastronomy.org 

If you do still need to email me: nabil.freij@gmail.com

2023-02-27 18:36 UTC, wtbarnes requested changes
I've taken the approach here of making any input to `wcs.world_to_pixel` unit-less when it is used *internally*. Externally, I've made no changes as I don't think that is within scope of this PR.

2023-02-27 18:36 UTC, wtbarnes commented on sunpy/map/maputils.py
>      edge_pixels = u.Quantity(np.concatenate(edges).value, unit=u.pix, copy=False)
```suggestion
    edge_pixels = np.concatenate(edges).value
```

2023-02-27 18:36 UTC, wtbarnes commented on sunpy/physics/differential_rotation.py
> +    c = smap.wcs.pixel_to_world(pixels[:, 0], pixels[:, 1])
```suggestion
    c = smap.wcs.pixel_to_world(pixels[:, 0].value, pixels[:, 1].value)
```

2023-02-27 18:36 UTC, wtbarnes commented on sunpy/physics/differential_rotation.py
>          input_pixels = xy.T * u.pix
```suggestion
        input_pixels = xy.T
```

2023-03-23 13:13 UTC, dstansby approved these changes

2023-03-23 15:32 UTC, nabobalis approved these changes

2023-03-23 15:32 UTC, merged

2023-03-23 15:33 UTC, nabobalis commented
Thanks again @ryuusama09