fixed mapbase autoalign
sunpy/sunpy pull request #6796
Opened 2023-02-24 19:51 UTC by Mihan786Chistie

Fixed the issue: [https://github.com/sunpy/sunpy/issues/6794](url)

2023-02-24 20:04 UTC, Mihan786Chistie commented
pre-commit.ci autofix

2023-02-24 20:09 UTC, Mihan786Chistie reviewed
Changed `ret = axes.pcolormesh(data, **imshow_args)` to
`ret = axes.pcolormesh(np.arange(data.shape[1] + 1) - 0.5,
                                  np.arange(data.shape[0] + 1) - 0.5,
                                  data, **imshow_args)`

2023-02-24 20:46 UTC, Mihan786Chistie commented
Can @ayshih review the changes made are ok?

2023-02-24 21:37 UTC, nabobalis commented
Hi @Mihan786Chistie, thanks for the pull request.

A few things need to occur with this bugfix. 

1. You will need to add a bugfix changelog entry following these instructions: https://github.com/sunpy/sunpy/blob/main/changelog/README.rst
2. This change has changed the figure hashes used by ci/circleci. You can see the output here: https://app.circleci.com/pipelines/github/sunpy/sunpy/20284/workflows/bbaff9b2-a494-4580-9d13-ccf9d50902c5/jobs/83621

This needs to be changed for both files we have: https://github.com/sunpy/sunpy/blob/main/sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json and https://github.com/sunpy/sunpy/blob/main/sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json

The docbuild failure you can ignore, that was my fault.

2023-02-25 08:41 UTC, Mihan786Chistie commented
I think I understood how to add changelog, but I am confused how to fix the ci/circleci test an what to change in both the file https://github.com/sunpy/sunpy/blob/main/sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json and https://github.com/sunpy/sunpy/blob/main/sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json. Can you explain bit of the process?

2023-02-25 16:52 UTC, Mihan786Chistie commented
@nabobalis please review this PR

2023-02-25 17:00 UTC, nabobalis commented
> @nabobalis please review this PR

Please do not @ people unless it is urgent.

2023-02-25 17:01 UTC, nabobalis commented on changelog/6796.bugfix.rst
> +Fixed a bug in ### sunpy/map/mapbase.py file to supply the pixeledges to the ####pcolormesh() function explicitly while calling pcolormesh() function, so it does not treat integer pixels as pixel edg
```suggestion
When using ``autoalign=True`` when plotting maps, the result was off by half a pixel as the ``pcolormesh`` call was not supplying the pixel edges explicitly.
```

2023-02-26 04:14 UTC, ayshih requested changes
Please add the following new figure test to the bottom of the file `sunpy/map/tests/test_plotting.py`:
```python
@figure_test
def test_plot_autoalign_pixel_alignment(aia171_test_map):
    # Verify that autoalign=True does not affect pixel alignment
    x, y = [z.value for z in aia171_test_map.reference_pixel]

    fig = Figure(figsize=(10, 4))

    ax1 = fig.add_subplot(121, projection=aia171_test_map)
    aia171_test_map.plot(axes=ax1, autoalign=False, title='autoalign=False')
    ax1.grid(False)
    ax1.set_xlim(x - 2, x + 2)
    ax1.set_ylim(y - 2, y + 2)

    ax2 = fig.add_subplot(122, projection=aia171_test_map)
    aia171_test_map.plot(axes=ax2, autoalign=True, title='autoalign=True')
    ax2.grid(False)
    ax2.set_xlim(x - 2, x + 2)
    ax2.set_ylim(y - 2, y + 2)

    return fig
```

The current, bugged code produces (the panels are supposed to match):
![Figure_1](https://user-images.githubusercontent.com/991759/221392011-fb938cba-de69-44e6-a0ab-3b9237df3bd2.png)

2023-02-26 13:18 UTC, Mihan786Chistie commented
pre-commit.ci autofix

2023-02-26 16:44 UTC, nabobalis commented on sunpy/map/tests/test_plotting.py
> +def test_plot_autoalign_pixel_alignment(aia171_test_map):
You will need to add this hash to the two figure hash files. You can get the hash and test name from the failed CircleCi runs.

2023-02-27 03:23 UTC, ayshih approved these changes
Just one suggestion on the changelog entry, otherwise looks good to me

2023-02-27 03:23 UTC, ayshih commented on changelog/6796.bugfix.rst
> +When using ``autoalign=True`` when plotting maps, the result was off by half a pixel as the ``pcolormesh`` call was not supplying the pixel edges explicitly.
```suggestion
When using ``autoalign=True`` when plotting maps, the result was misaligned by half a pixel.
```
There's no particular benefit here to providing detail

2023-02-27 06:00 UTC, nabobalis approved these changes

2023-02-27 06:32 UTC, merged

2023-02-27 06:32 UTC, nabobalis commented
Thanks @Mihan786Chistie for the PR and @ayshih for the review.

2023-02-27 06:39 UTC, Mihan786Chistie commented
Thanks @nabobalis and @ayshih for guiding me through and approving my PR.