Tweak lon_lat example to have correct lon and lat lines
sunpy/sunpy pull request #6832
Opened 2023-03-09 20:01 UTC by nabobalis

Someone pointed out we had the wrong lon,lat lines. 

I also updated some text and renamed the file.

2023-03-09 21:31 UTC, ayshih requested changes
A bunch of tweaks.

Also, I'm not inclined to rename the filename because that makes it much more cumbersome to see the same example at different versions of sunpy (e.g., by selecting different versions in our online docs).

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
> +This example demonstrates how you can draw your own Stonyhurst
```suggestion
This example demonstrates how you can draw individual Stonyhurst
```

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
> +# We first create a map using the sample data.
```suggestion
# We will first demonstrate the coordinate transformations that occur under the
# hood to show a heliographic grid line of longitude or latitude.
# Let's start with a map using the sample data.
```

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
> +# Let's first specify a single heliographic point coordinate.
```suggestion
# We can define a heliographic coordinate for a single point.
```

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
>                               frame=frames.HeliographicStonyhurst)
```suggestion
```suggestion
lon_value = 35 * u.deg
lat_value = 12 * u.deg
stonyhurst_frame = frames.HeliographicStonyhurst(obstime=aia.date)
point_in_stonyhurst = SkyCoord(lon=lon_value, lat=lat_value, frame=stonyhurst_frame)
```

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
> +# Next we transform it into the coordinate frame of our map which is helioprojective.
```suggestion
# Next we transform it into the coordinate frame of our map, which is helioprojective.
```

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
>  print(hpc_stonyhurst_center)
```suggestion
point_in_hpc = point_in_stonyhurst.transform_to(aia.coordinate_frame)
print(point_in_hpc)
```

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
>  lon_value = 35 * u.deg
```suggestion
```
Because I moved the definition earlier

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
> +               np.ones(num_points) * lat_value, frame=frames.HeliographicStonyhurst)
```suggestion
constant_lon = SkyCoord(lon_value, np.linspace(-90, 90, num_points) * u.deg,
                        frame=stonyhurst_frame)
constant_lat = SkyCoord(np.linspace(-90, 90, num_points) * u.deg, lat_value,
                        frame=stonyhurst_frame)
```
The single value will automatically be broadcast, so there's no need to explicitly create an array of constant value.

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
> +# Now let's define two lines, one of constant longitude and one of constant latitude.
```suggestion
# Now let's define two lines, one of constant longitude and one of constant latitude,
# that pass through the previously defined coordinate point.
```

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
>  # Now let's plot the results. We'll overlay the autogenerated lon/lat
```suggestion
# Now let's plot the single coordinate point and the individual lines of
# constant longitude and latitude. We'll overlay the autogenerated lon/lat
```

2023-03-09 21:31 UTC, ayshih commented on examples/plotting/lon_lat_lines.py
> +ax.plot_coord(lat, color="tomato")
```suggestion
ax.plot_coord(lat, color="tomato")
ax.plot_coord(point_in_stonyhurst, marker="o")
```

2023-03-09 21:32 UTC, nabobalis commented
> Also, I'm not inclined to rename the filename because that makes it much more cumbersome to see the same example at different versions of sunpy (e.g., by selecting different versions in our online docs).

Oh that is a good point. I will undo the name change.

2023-03-09 21:34 UTC, nabobalis commented on examples/plotting/lat_lon_lines.py
> +ax.plot_coord(lat, color="tomato")
```suggestion
ax.plot_coord(constant_lon, color="lightblue")
ax.plot_coord(constant_lat, color="tomato")
```

2023-03-12 02:18 UTC, ayshih approved these changes

2023-03-12 02:19 UTC, merged