Move Fido tutorial up a doc level
sunpy/sunpy pull request #6872
Opened 2023-03-22 17:42 UTC by dstansby

I think it makes more sense to have this at the top level, with links to the data-provider specifcic docs at the top.

2023-03-22 17:57 UTC, hayesla approved these changes

2023-03-22 17:57 UTC, hayesla commented on docs/intro/acquiring_data/index.rst
> +This guide outlines how to search for and download data using the `~sunpy.net.Fido` interface for search and download.
```suggestion
This tutorial outlines how to search for and download data using the `~sunpy.net.Fido` interface for search and download.
```

maybe guide is the correct phrasing here, but maybe to be consistent tutorial would be better?

2023-03-22 17:57 UTC, hayesla commented on docs/intro/acquiring_data/index.rst
> +All the examples in this guide use ``Fido``, so lets start by importing it::
```suggestion
All the examples in this tutorial use ``Fido``, so lets start by importing it::
```

2023-03-22 17:57 UTC, hayesla commented on docs/intro/acquiring_data/index.rst
> +    >>> from sunpy.net import Fido, attrs as a
should we also mention here what "attrs" is given that its imported here too?

2023-03-22 17:57 UTC, hayesla commented on docs/intro/acquiring_data/index.rst
> +To see a summary of the results print the result variable that came back from the previous search::
```suggestion
To see a summary of the results, we can print the `result` variable that came back from the previous search::
```

2023-03-22 18:42 UTC, Cadair requested changes

2023-03-22 18:42 UTC, Cadair commented on docs/intro/acquiring_data/index.rst
>      sample-data
This feels out of place in this list lol

2023-03-22 18:42 UTC, Cadair commented on docs/intro/acquiring_data/index.rst
> +Fido supports a number of different remote data sources. To see a list the Fido object can be printed::
```suggestion
Fido supports a number of different remote data sources.
To see a list the Fido object can be printed::
```

2023-03-22 18:42 UTC, Cadair commented on docs/intro/acquiring_data/index.rst
> +These values are updated with every release of sunpy, so may not be quite up to date!
```suggestion
These values are updated with every release of sunpy, so may not be quite up to date.
```

2023-03-22 18:42 UTC, Cadair commented on docs/intro/acquiring_data/index.rst
> +These attributes also support tab-completion to auto to auto-fill the attribute name, for example typing ``a.jsoc.aia_f<TAB>`` in a jupyter notebook will show you the available attributes that start
```suggestion
These attributes also support tab-completion to auto to auto-fill the attribute name, for example typing ``a.jsoc.aia_f<TAB>`` will show you the available attributes that start with "aia_f".
```

2023-04-01 19:57 UTC, nabobalis commented
Looks like a legit doc test failure

```
_____________________________ [doctest] index.rst ______________________________
[gw0] linux -- Python 3.11.2 /home/runner/work/sunpy/sunpy/.tox/py311/bin/python
027     >>> from sunpy.net import Fido, attrs as a
028 
029 .. contents::
030     :depth: 3
031 
032 Fido supports a number of different remote data sources. To see a list the Fido object can be printed:
033 
034 .. code-block:: python
035 
036     >>> print(Fido)
```

2023-04-05 20:06 UTC, merged