Clean up time tutorial
sunpy/sunpy pull request #6920
Opened 2023-04-15 20:45 UTC by dstansby

Fixes https://github.com/sunpy/sunpy/issues/6863. Not perfect, but a lot better and good enough for 5.0 I think.

2023-04-16 02:31 UTC, nabobalis commented on docs/tutorial/time.rst
> +To handle all these formats, sunpy has the `sunpy.time.parse_time()` that accepts a variety of inputs, and returns a consistent `~astropy.time.Time` object.
```suggestion
To handle all these formats, sunpy has the :meth:`sunpy.time.parse_time` that accepts a variety of inputs, and returns a consistent `~astropy.time.Time` object.
```

2023-04-16 06:19 UTC, nabobalis commented on docs/tutorial/time.rst
> +`~sunpy.time.TimeRange` makes use of parse_time() so it can accept a wide variety of time formats.
```suggestion
`~sunpy.time.TimeRange` makes use of :meth:`sunpy.time.parse_time` so it can accept a wide variety of time formats.
```

2023-04-18 04:37 UTC, nabobalis approved these changes

2023-04-23 15:19 UTC, nabobalis commented
I think this is worth merging with one review.

2023-04-24 16:49 UTC, wtbarnes commented on sunpy/time/time.py
> +        We support the same formats as `astropy.time.Time`, which are are::
```suggestion
        We support the same formats as `astropy.time.Time`, which are::
```

2023-04-24 18:35 UTC, wtbarnes commented
I agree that this is an improvement over what was here previously, but I think this section of the tutorial could still do with some major restructuring. Currently, it still is in a more how-to format than tutorial. In particular, I think this section could be structured in three sections:

1. Parsing time
2. Arithmetic with time
3. Time ranges

In section 1, we could parse two times (from different formats), perform some (very basic) arithmetic with them in section 2, and then construct a time range from them in section 3.

2023-04-24 18:40 UTC, wtbarnes commented on docs/tutorial/time.rst
> +    >>> parse_time(datetime.datetime(2007, 5, 4, 21, 8, 12))
```suggestion
```

2023-04-24 18:40 UTC, wtbarnes commented on docs/tutorial/time.rst
>      <Time object: scale='utc' format='datetime' value=2007-05-04 21:08:12>
```suggestion
```

2023-04-24 18:40 UTC, wtbarnes commented on docs/tutorial/time.rst
>      <Time object: scale='utc' format='isot' value=2007-05-04T21:08:12.000>
```suggestion
```

2023-04-24 18:41 UTC, wtbarnes commented on docs/tutorial/time.rst
>      <Time object: scale='utc' format='isot' value=2007-05-04T21:08:12.000>
I do not think we need to show a bunch of different time formats. That is what the how-to and reference are for.

2023-04-24 18:41 UTC, wtbarnes commented on docs/tutorial/time.rst
> +A TimeRange object can be created by providing a start time and an end time::
```suggestion
A `sunpy.time.TimeRange` object can be created by providing a start time and an end time::
```

2023-04-24 18:44 UTC, wtbarnes requested changes
I agree that this is an improvement over what was here previously, but I think this section of the tutorial could still do with some major restructuring. Currently, it still is in a more how-to format than tutorial. In particular, I think this section could be structured in three sections:

1. Parsing time
2. Arithmetic with time
3. Time ranges

In section 1, we could parse two times (from different formats), perform some (very basic) arithmetic with them in section 2, and then construct a time range from them in section 3.

We are pretty late in the game for 5.0 so if these changes feel like to much for this PR, I'm ok punting this larger rewrite to 5.1.

2023-04-27 13:56 UTC, wtbarnes approved these changes
I'll create another issue with my other suggestions. I think this is a big improvement and is a better compliment to our new how-to for parsing time.

2023-04-27 13:56 UTC, wtbarnes commented on docs/tutorial/time.rst
>      >>> import datetime
```suggestion
```

I don't think this is used anywhere.

2023-04-28 21:48 UTC, nabobalis approved these changes

2023-04-28 21:49 UTC, merged