Now pass kwargs into the downloader for JSOC only fetches
sunpy/sunpy pull request #6921
Opened 2023-04-16 06:15 UTC by nabobalis

We never prevented more than one connection to the JSOC and I think this is why we now hit the rate limit.

Hopefully fixes https://github.com/sunpy/sunpy/issues/6510 again

2023-04-16 09:42 UTC, dstansby requested changes
Amazing, thanks! Could you stick in a bugfix changelog entry, and then this looks good to go.

2023-04-16 15:17 UTC, Cadair requested changes
I don't think this is the correct approach. Passing kwargs to both `Downloader` and the `client.fetch` method sounds fraught with trouble.

I think the answer is to not pass `**kwargs` but to pass `max_splits` explicitly.

2023-04-18 04:42 UTC, nabobalis commented
Added a changelog and only now pass in max_spiits.

2023-04-18 15:13 UTC, nabobalis commented
> Am I mistaken in thinking we aren't doing anything with this either: [`main`/sunpy/net/jsoc/jsoc.py#L485](https://github.com/sunpy/sunpy/blob/main/sunpy/net/jsoc/jsoc.py?rgh-link-date=2023-04-18T07%3A38%3A35Z#L485)

Yeah we didnt, should be fixed now.

2023-04-18 16:26 UTC, Cadair approved these changes
Looks good.

We should fix this test as well: https://github.com/sunpy/sunpy/actions/runs/4733988353/jobs/8402592079?pr=6921#step:10:5325

2023-04-18 16:51 UTC, nabobalis commented
I fixed that in another PR just to be tricky.

2023-04-18 16:52 UTC, merged