Add how-to example for manipulating grid lines in images.
sunpy/sunpy pull request #6978
Opened 2023-04-27 09:28 UTC by DanRyanIrish

## PR Description

This PR adds a how-to file for manipulating grid lines in outputs of `Map.plot`.

2023-04-27 13:39 UTC, wtbarnes commented
I think you're going to want to use the plot directive for this one so that your plots show up inline: https://matplotlib.org/stable/api/sphinxext_plot_directive_api.html.

2023-05-04 12:47 UTC, hayesla requested changes

2023-05-04 12:47 UTC, hayesla commented on docs/how_to/manipulate_grid_lines.rst
> +Manipulate Grids Lines in Image Plots
```suggestion
Manipulate Grids Lines when plotting Map with WCSAxes
```

2023-05-04 12:47 UTC, hayesla commented on docs/how_to/manipulate_grid_lines.rst
> +Changing Appearance of Heliocentric Grid
```suggestion
Changing Appearance of Heliographic Grid
```
i think this is heliographic rather than heliocentric right?

2024-03-21 02:36 UTC, nabobalis commented
Do we want more examples? Clip the figures so they aren't so dark?

2024-03-21 03:31 UTC, wtbarnes commented
I think so. Or use a different image? The figure is so dark that you can't see the grid lines. I wonder if it would be useful to add a section showing how to change the styling of the grid lines as well.

2024-03-21 04:49 UTC, nabobalis commented
> I think so. Or use a different image? The figure is so dark that you can't see the grid lines. I wonder if it would be useful to add a section showing how to change the styling of the grid lines as well.

I am going to switch the image to a HMI file, that should allow the grid to shine through.

Is the last one not changing the style? It does linewidth and line style, is there more we want to cover?

2024-03-21 05:46 UTC, nabobalis commented
I changed it.

2024-03-21 05:46 UTC, nabobalis approved these changes

2024-03-25 04:51 UTC, wtbarnes reviewed
Now looking at this, I'm wondering why we want this in our docs. Are we not just duplicating a small part of the already existing WCSAxes examples? Why not just link to them? The only exception is the last section using `draw_grid` and if we limit it to that it's not really a how-to guide. I'm not saying there isn't a version of this that can justifiably live in our docs, but I don't see the utility of it at the moment.

2024-03-25 04:51 UTC, wtbarnes commented on docs/how_to/manipulate_grid_lines.rst
> +Instead is accepts keyword arguments and transparently passes them onto the underlying infrastructure.
```suggestion
Instead it accepts keyword arguments and transparently passes them onto the underlying infrastructure.
```

2024-03-25 04:53 UTC, wtbarnes commented
Also is the choice to repeat the whole code block (as opposed to sharing context between them) intentional? If so, that's ok, but we should ensure we're doing this for all how-to guides, ie I can copy the whole block of code and it works without needing to paste from any code blocks above.

2024-03-25 05:15 UTC, nabobalis commented
> Also is the choice to repeat the whole code block (as opposed to sharing context between them) intentional? If so, that's ok, but we should ensure we're doing this for all how-to guides, ie I can copy the whole block of code and it works without needing to paste from any code blocks above.

I thought that any code in a plot block was not shared between other blocks, it was standalone. I will have to check the MPL docs to be sure.

2024-03-25 05:16 UTC, nabobalis commented
> Now looking at this, I'm wondering why we want this in our docs. Are we not just duplicating a small part of the already existing WCSAxes examples? Why not just link to them? The only exception is the last section using `draw_grid` and if we limit it to that it's not really a how-to guide. I'm not saying there isn't a version of this that can justifiably live in our docs, but I don't see the utility of it at the moment.

I think showing how WCSAxes affects a solar plot has merit over seeing how it works for a set of data that isn't solar. But I won't fight it, I can reduce it to basic and maybe turn it into a gallery example?

2024-03-25 17:52 UTC, nabobalis commented
See if you prefer this version.

2024-03-25 17:55 UTC, nabobalis commented on docs/how_to/manipulate_grid_lines.rst
> +=====================================================
```suggestion
*****************************************************
Manipulate grids lines when plotting Map with WCSAxes
*****************************************************
```

2024-03-25 17:55 UTC, nabobalis commented on docs/how_to/manipulate_grid_lines.rst
> +------------------------------------
```suggestion
Turning off the Helioprojective grid
====================================
```

2024-03-25 17:55 UTC, nabobalis commented on docs/how_to/manipulate_grid_lines.rst
> +-----------------------------------------------
```suggestion
Changing the appearance of Helioprojective grid
===============================================
```

2024-03-25 17:55 UTC, nabobalis commented on docs/how_to/manipulate_grid_lines.rst
> +--------------------------------------------
```suggestion
Changing the appearance of Heliographic grid
============================================
```

2024-03-25 18:27 UTC, nabobalis commented on docs/how_to/manipulate_grid_lines.rst
> +*****************************************************
```suggestion
*****************************************
Manipulate grids lines when plotting Maps
*****************************************
```

2024-04-24 15:19 UTC, merged