Replace some TOC headings with raw html to fix sidebar.
sunpy/sunpy pull request #6991
Opened 2023-05-04 19:22 UTC by alasdairwilson

This partially solves #6989

The issue is caused by headings in the tutorial/how to page becoming top level toc entries, by turning these into raw html headings this behaviour is avoided.

The issue also has a comment regarding the coords TOC but this can't be tackled till after #6954

2023-05-04 21:27 UTC, nabobalis approved these changes

2023-05-05 13:29 UTC, dstansby requested changes
This seems a bit hacky, and not a sustainable solution if/when the pages get modified. What happens if the toctrees are moved above the first heading on the page instead? Maybe then they'll be treated as children of the page they're on, instead of children of a section within that page.

2023-05-05 13:32 UTC, Cadair commented
> This seems a bit hacky

oh yes.

> not a sustainable solution if/when the pages get modified

Why specifically? Yes it's weird, but it's just inline content, we aren't breaking references or anything else with this hack.

> What happens if the toctrees are moved above the first heading on the page instead?

This works fine, but then you either have the whole contents list above the intro which is weird, or you don't have the contents list in the index page at all (i.e. make the toctree hidden).

2023-05-05 13:36 UTC, dstansby commented
I was thinking more from the point of view of new contributiors (or old ones) coming along later and wondering why these aren't just RST headings.

Alternative fix, we could just drop the headings altogether? They don't seem super neccesary to have.

2023-05-05 13:37 UTC, Cadair commented
My solution was going to be to make them bold.

2023-05-05 14:17 UTC, alasdairwilson commented
One solution that came to mind would be to have a hidden toctree for the sidebar and then a manually generated listed that looks like the current section listing but this is hard to maintain because future changes to the toc or ordering of the sections aren't changed in both places automatically.

Despite this being hacky, I think this html solution is maintainable. I think it is clear even by a glance at what the sphinx directive is doing, inserting a heading into the generated html, and it would be pretty much impossible to break them regardless of where the toc on this page is moved. Someone might not be able to work out why regular rst section headings aren't being used but I don't think its that obtuse, certainly not the most egregious patch anyway, (and if they changed them to rst headings they would probably immediately clock the reasoning).

I don't mind the headings going (or going bold) but I do think that the page is better with the headings than without so the question is is the tradeoff of using this directive and perhaps being unclear worth it.

2023-05-05 14:18 UTC, dstansby commented
I'd be 👍 just making them bold

2023-05-05 14:30 UTC, wtbarnes commented
> I'd be 👍 just making them bold

I'm in this camp too I think. I think the headings are still obvious, especially since they are mostly at the top of the page anyway.

2023-05-05 15:28 UTC, wtbarnes commented
Do we want to hold this up until #6954 is merged so it can fix those headings too?

2023-05-05 15:30 UTC, dstansby approved these changes

2023-05-05 21:47 UTC, nabobalis commented
> Do we want to hold this up until #6954 is merged so it can fix those headings too?

I don't see why not, might as well do it all in one go.

2023-05-10 16:03 UTC, Cadair approved these changes

2023-05-10 16:03 UTC, merged