Patch broken import for private io modules
sunpy/sunpy pull request #7020
Opened 2023-05-24 09:09 UTC by nabobalis

This should make the modules actually importable now.

2023-05-25 07:27 UTC, jgieseler commented
> Why does moving these imports fix the issue?

It's not the moving, but adding a dot before the underscore: from `._`cdf import *

2023-05-25 08:04 UTC, nabobalis commented
I added some unit tests to check importlib can import the old modules.

2023-05-30 20:49 UTC, dstansby requested changes
Instead of blanked ignoring the warning in the test config, the warnings should be caught or filtered in the new tests, to make sure no-one accidentally uses the deprecated API anywhere else in the package.

2023-06-01 23:03 UTC, nabobalis commented
```
ERROR sunpy/io/cdf.py - sunpy.util.exceptions.SunpyDeprecationWarning: The `sunpy.io.cdf` module is deprecated, as it was designed for internal use.
ERROR sunpy/io/file_tools.py - sunpy.util.exceptions.SunpyDeprecationWarning: The `sunpy.io.file_tools` module is deprecated, as it was designed for internal use.
ERROR sunpy/io/jp2.py - sunpy.util.exceptions.SunpyDeprecationWarning: The `sunpy.io.jp2` module is deprecated, as it was designed for internal use.
```
My understanding is that pytest is importing the Python files and that triggers the warnings causing the test suite to fail. I do not know how to deal with that without using the ignore section of setup.cfg.

2023-06-08 21:31 UTC, wtbarnes commented on setup.cfg
> +    ignore:.*module is deprecated, as it was designed for internal use
I'm not comfortable with it, but I don't have a better suggestion.

2023-06-08 21:32 UTC, wtbarnes approved these changes

2023-06-12 10:58 UTC, dstansby requested changes
I think I've found a way to avoid having the global warning ignores: https://github.com/nabobalis/sunpy/pull/1

2023-06-12 15:10 UTC, dstansby approved these changes
👍 if CI passes. The devdeps figure test fail looks un-related

2023-06-12 16:37 UTC, merged