Fix bug in get_horizons_coord time dictionary arg
sunpy/sunpy pull request #7106
Opened 2023-07-18 12:09 UTC by samaloney

## PR Description

Fix small bug in get_horizons_coord when time is specified using the dictionary format. Update code to pass full time spec (including milliseconds) to astroquery.

Closes #7105

2023-07-18 13:18 UTC, ayshih requested changes
Can you also add a line to convert the returned obstime back to UTC when a dictionary is input?  That is, add a line after this one:
https://github.com/sunpy/sunpy/blob/64419c2d335695bf99d9a1ebdb457d3d47b22bc5/sunpy/coordinates/ephemeris.py#L329

2023-07-18 13:18 UTC, ayshih commented on changelog/7106.bugfix.rst
> +Fix bug in `sunpy.coordinates.get_horizons_coord` when specifying the time using a dictionary, the returned times now match the supplied times.
```suggestion
Fix bug in `sunpy.coordinates.get_horizons_coord` when specifying a time range via a dictionary that could cause the returned times to be slightly different from the supplied times.
```

2023-08-18 15:59 UTC, ayshih requested changes

2023-08-18 15:59 UTC, ayshih commented on sunpy/coordinates/ephemeris.py
> +        obstime = obstime_tdb.utc
```suggestion
        obstime = Time(obstime_tdb, format='isot', scale='utc')
```
Also add `from astropy.time import Time` up top.  I'd wager that most solar users would rather see times in ISOT format than in JD format.

2023-08-18 15:59 UTC, ayshih commented on sunpy/coordinates/tests/test_ephemeris.py
> +    assert_array_equal(e_ref.obstime.utc.isot, e.obstime.utc.isot)
```suggestion
    assert e.obstime.format == 'isot'
    assert e.obstime.scale == 'utc'
    assert_array_equal(e_ref.obstime.utc.isot, e.obstime.utc.isot)
```

2023-08-18 15:59 UTC, ayshih commented on changelog/7106.bugfix.rst
> +Fix bug in `sunpy.coordinates.get_horizons_coord` when specifying a time range via a dictionary that could cause the returned times to be slightly different from the supplied times.
```suggestion
Fix bug in :func:`~sunpy.coordinates.get_horizons_coord` when specifying a time range via a dictionary that could cause the returned times to be slightly different from the supplied times.
```

2023-08-29 12:15 UTC, ayshih approved these changes
Looks good to me!

2023-08-31 13:36 UTC, dstansby approved these changes

2023-08-31 13:36 UTC, merged