Internal functions for coordinate transformations are now private API
sunpy/sunpy pull request #7113
Opened 2023-07-26 13:24 UTC by ayshih

The various internal functions for coordinate transformations (e.g., `hgs_to_hgc()`) were never intended to be used directly by users.  This PR makes the file private API by renaming `transformations.py` to `_transformations.py`.  There are two user-facing context managers in that file (`transform_with_sun_center()` and `propagate_with_solar_surface()`), but those have always been imported one level up and documented as part of the API there.

Is deprecation needed here?

2023-07-28 11:13 UTC, Cadair commented
> Is deprecation needed here?

yes, I think if we are tacitly admitting that it *was* public API then it needs to be deprecated.

2023-07-28 15:17 UTC, Cadair approved these changes

2023-08-17 19:07 UTC, nabobalis commented
pytest fails with:

```
ERROR ../../.tox/py311/lib/python3.11/site-packages/sunpy/coordinates/transformations.py
ERROR ../../.tox/py311/lib/python3.11/site-packages/sunpy/coordinates/transformations.py
```
The deprecation warning is failing the CI, I think we need to add it to the pytest ignore list in setup.cfg

2023-08-31 13:37 UTC, dstansby submitted a review, later dismissed
Requesting changes so this isn't merged with broken CI

2023-10-16 20:40 UTC, dstansby requested changes
I think this needs a second changelog entry to mention the user facing functions in `sunpy.coordinates.transformations` that have been moved. Even if they are in the `sunpy.coordinates` namespace there could be someone who was importing them from `...transformations`.

2023-10-16 20:40 UTC, dstansby commented on sunpy/coordinates/transformations.py
> +                "for internal use.")
```suggestion
warn_deprecated("The `sunpy.coordinates.transformations` module is deprecated, as it was designed "
                "for internal use. "
                "transform_with_solar_centre() and propagate_with_solar_surface() can be imported from sunpy.coordinates")
```

2023-10-17 13:00 UTC, wtbarnes commented
I think the docs build is still failing…I gave up trying to fix this last week because I have no idea what the problem is and can't reproduce locally.

2023-10-17 14:40 UTC, ayshih commented on sunpy/coordinates/transformations.py
> +                "for internal use.")
Done with slightly different text

2023-10-17 16:38 UTC, dstansby approved these changes

2023-10-17 21:22 UTC, merged