Prioritize hgln_obs over crln_obs when extracting observer information from FITS headers
sunpy/sunpy pull request #7188
Opened 2023-09-08 19:00 UTC by svank

Fix as proposed in #7184

Thanks @ayshih for confirming this should be right!

2023-09-10 17:49 UTC, dstansby requested changes
Looks 👍 , just one request for a comment, and needs a bugifx changelog entry adding.

2023-09-10 17:49 UTC, dstansby commented on sunpy/coordinates/wcs_utils.py
> +            break
Could you add a quick comment above where the `required_attrs` dictionary is defined that the order of entries matters there?

2023-09-11 15:19 UTC, svank commented
@dstansby Thanks! I've made these changes.

2023-09-11 20:05 UTC, ayshih requested changes
Some text edits, otherwise looks good to me!

If I were to be super-picky, the part of the unit test that tests the prioritization in the `Map` implementation should really live under `sunpy.map.tests` and not `sunpy.coordinates.tests`, because the relevant code – how `GenericMap` prioritizes and sanitizes the observer location – all lives in `sunpy/map/mapbase.py`.

2023-09-11 20:05 UTC, ayshih commented on sunpy/coordinates/tests/test_wcs_utils.py
> +    code paths, so test them both.
```suggestion
    `Map` creates a custom FITS header with a sanitized observer location, so
    we need to also test a directly instantiated `WCS` object.
```

2023-09-12 07:34 UTC, Cadair commented
>  the part of the unit test that tests the prioritization in the Map implementation should really live under sunpy.map.tests

Given my recent foray into seeing if it's possible to run tests for subpackages without optional dependencies installed, ideally we would not have a direct reliance on map in the coordinates tests.

2023-09-12 21:36 UTC, svank commented
What's code review for, if not being picky? I moved the `Map` part of the test to the `map` module---there is still a pre-existing `Map` dependence in `coordinates/tests/test_wcs_utils.py`, but now I avoid further entrenching that.

Text edits are also implemented.

2023-09-15 14:25 UTC, ayshih approved these changes
Looks good to me!

2023-09-15 20:02 UTC, merged

2023-09-15 20:02 UTC, ayshih commented
Thanks, @svank!