Remove old limb drawing function
sunpy/sunpy pull request #7202
Opened 2023-09-16 16:26 UTC by dstansby

Deprecated in 4.1, so time to 🗑️

2023-09-18 10:49 UTC, hayesla approved these changes
looks good, just an update the changelog name and then good to go

2023-10-09 16:08 UTC, Cadair approved these changes

2023-10-09 16:09 UTC, Cadair requested changes
The doc build fail is real

2023-10-09 18:35 UTC, Cadair approved these changes
:shipit:  thanks @wtbarnes

2023-10-09 18:35 UTC, merged