Fix issue when `transform` keyword passed to `GenericMap.draw_contours()`
sunpy/sunpy pull request #7207
Opened 2023-09-18 15:41 UTC by hayesla

Fixes #7191 

I think this now address the issue outlined

2023-09-18 20:26 UTC, ayshih reviewed
Needs a unit test, of course, which will presumably have to be a figure test

2023-09-18 20:26 UTC, ayshih commented on sunpy/map/mapbase.py
> +                contour_args.pop("transform")
```suggestion
                transform_orig = contour_args.pop("transform")
```

2023-10-16 20:49 UTC, dstansby requested changes
Looks like this still needs a test adding.

2024-01-31 19:13 UTC, nabobalis commented
Superseded by https://github.com/sunpy/sunpy/pull/7427

2024-01-31 19:13 UTC, closed without merging