Parse more `wavelnth` comments for units
sunpy/sunpy pull request #7245
Opened 2023-10-19 02:08 UTC by wtbarnes

This adds yet another possible case when extracting the wavelength unit from the key comment on `WAVELNTH` in `extract_waveunit`. The inspiration for this is #7220, specifically this comment: https://github.com/sunpy/sunpy/pull/7220#discussion_r1364771658

2023-10-22 17:58 UTC, dstansby requested changes
Could do with with a quick test adding for the new pattern?

2023-10-22 18:31 UTC, wtbarnes commented
> Could do with with a quick test adding for the new pattern?

I agree. #7220 provides a test FITS header that is a good test case for this. For convenience, could we merge this and then I'll add a test for this extra case to #7220?

2023-10-23 09:54 UTC, dstansby approved these changes

2023-10-24 17:42 UTC, nabobalis approved these changes

2023-10-24 17:42 UTC, merged