Seperate docs into docs and docs-gallery
sunpy/sunpy pull request #7267
Opened 2023-10-26 23:37 UTC by nabobalis

Following the problems of installing mplcario, I have separate docs into docs and docs-gallery. Only docs is installed for the dev extra.

2023-10-26 23:40 UTC, nabobalis commented on setup.cfg
> +docs-gallery =
I think thius is everything.

2023-10-27 06:07 UTC, alasdairwilson approved these changes

2023-10-27 09:05 UTC, dstansby requested changes
👍  - the fact that you now need to install the [docs-gallery] extra to build the gallery should be documented somewhere in the developer guide.

2023-10-27 09:42 UTC, Cadair commented on docs/dev_guide/contents/newcomers.rst
> +    # Note you might need to add python=<version> if a new one has come out very recently.
```suggestion
    # Note you might need to add python=<version> if a new release of Python has come out very recently.
```

2023-10-27 14:50 UTC, nabobalis commented
> 👍 - the fact that you now need to install the [docs-gallery] extra to build the gallery should be documented somewhere in the developer guide.

Should be fixed hopefully.

2023-10-27 15:06 UTC, Cadair approved these changes

2023-10-27 15:35 UTC, dstansby approved these changes

2023-10-27 15:35 UTC, merged