Add prettier precommit
sunpy/sunpy pull request #7334
Opened 2023-12-06 18:37 UTC by nabobalis

2023-12-06 21:20 UTC, nabobalis commented on .github/workflows/stale_bot.yml
> +    #            ┌───────── minute (0 - 59)
I have to fix this

2023-12-07 11:36 UTC, dstansby requested changes
Can you exclude the autogenerated files in `sunpy/net`? They look fine and diff well as it is, and linting them will be a pain every time we update them. Otherwise 👍 to doing this to the rest of the files

2023-12-07 11:37 UTC, dstansby reviewed
Oh also `zenodo.json` is autogenerated, so that should be excluded too.

2023-12-07 14:04 UTC, nabobalis commented
I disagree, we create the two attrs JSON and they should either have the output adjusted to look like the prettier output or they should be linted by the pre-commit.

2023-12-07 16:27 UTC, dstansby commented
Why? They're nicely human readable as they are, what's the point in applying an arbitrary linter to them and making our lives harder by having to modify the scripts that generate the files?

2023-12-07 18:10 UTC, nabobalis commented
> Why? They're nicely human readable as they are, what's the point in applying an arbitrary linter to them and making our lives harder by having to modify the scripts that generate the files?

I think they are much nicer to read in this form than before.

2024-01-04 21:15 UTC, wtbarnes commented
I'm not going to die on this hill, but I don't really see the utility in this.

2024-01-04 23:19 UTC, closed without merging

2024-01-04 23:19 UTC, nabobalis commented
In that case, I will close this and never bring it up ever again.