Double check a value was provided to jsoc notify
sunpy/sunpy pull request #7342
Opened 2023-12-08 22:14 UTC by nabobalis

This catches me out when running examples.

2023-12-28 01:40 UTC, nabobalis commented on sunpy/net/jsoc/attrs.py
> +                             "to be a valid email address: {value}")
```suggestion
                             "to be a valid email address")
```

2024-01-02 15:48 UTC, dstansby requested changes
👍 , with a suggestion and question.

2024-01-02 15:48 UTC, dstansby commented on sunpy/net/jsoc/attrs.py
> +        if not value:
```suggestion
        if value is None:
```
Is a bit clearer (if `value` is indeed `None` if no email is passed...

2024-01-02 15:48 UTC, dstansby commented on changelog/7342.trivial.rst
> +`~sunpy.net.jsoc.attrs.Notify` checks for a valid input value.
```suggestion
`~sunpy.net.jsoc.attrs.Notify` checks that a valid email address has been given as a value.
```
Does this have any other higher-level user facing behaviour that needs mentioning? e.g. if I forget to do a JSOC Fido search with an email address, does this now raise a more helpful error?

2024-01-02 15:48 UTC, dstansby approved these changes
Woops, that was meant to be an approval...

2024-01-04 20:43 UTC, wtbarnes approved these changes

2024-01-04 23:45 UTC, merged