Fix but which cause Fido to crash if SSL verification failed
sunpy/sunpy pull request #7446
Opened 2024-02-12 11:02 UTC by samaloney

* Now logs a message and return no result for HelioClient

# Thank you for contributing to SunPy

## 🚨 IMPORTANT 🚨

We know that working on code and submitting pull requests takes effort, and we appreciate your time.
Thank you.

[Please be aware that everyone has to follow our code of conduct](https://sunpy.org/coc)

[Furthermore, you might need to check with your work place if you are allowed to contribute code](https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html)

- Please try to create an issue _before_ creating a Pull Request.
- Please use the following Git commit message style
  - Use the future tense ("Adds feature" not "Added feature")
  - Limit the first line to 72 characters or less

We have several automatic features that run when a pull request is open.
They can appear daunting but do not worry about them!
[This a brief explanation of them.](https://docs.sunpy.org/en/latest/dev_guide/contents/pr_review_procedure.html#continuous-integration)

## ↑👆 DELETE above _before_ submitting 👆↑

## PR Description

2024-02-12 11:25 UTC, samaloney commented
This is what happens with this PR, not sure why the log message is showing up twice?

```
from sunpy.net import Fido, attrs as a
query = Fido.search(a.Time('2024-02-09T12:00', '2024-02-09T14:30'))

WARNING: SSL verification error for HEC client.
You can set the 'NO_VERIFY_HELIO_SSL' environment variable disable SSL verification for Helio. [sunpy.net.helio.hec]
2024-02-12 11:20:14 - sunpy - WARNING: SSL verification error for HEC client.
You can set the 'NO_VERIFY_HELIO_SSL' environment variable disable SSL verification for Helio.
```

2024-02-12 15:28 UTC, samaloney commented on sunpy/net/helio/tests/test_helio.py
> +@mock.patch('sunpy.net.helio.hec.Client', side_effect=SSLError('asdfa'))
```suggestion
@mock.patch('sunpy.net.helio.hec.Client', side_effect=SSLError('Test SSL Error'))
```

2024-02-12 16:18 UTC, nabobalis approved these changes

2024-02-12 16:19 UTC, nabobalis requested changes
CI to be fixed first

2024-02-12 18:05 UTC, nabobalis approved these changes

2024-02-12 18:08 UTC, Cadair commented
I am not adverse to this PR as is, but I do wonder if it would be worth looking at a generic solution? What's the failure mode if all VSO WDSL files are offline for example?

2024-02-12 18:08 UTC, samaloney commented on changelog/7446.bugfix.rst
> +Fix a bug which caused `Fido.search` to crash due to SSL certificate verification error for the `HelioClient`, now returns no result for the `HelioClient` in this case.
Where does this show up the docs build?

2024-02-12 18:11 UTC, nabobalis commented on changelog/7446.bugfix.rst
> +Fix a bug which caused `Fido.search` to crash due to SSL certificate verification error for the `HelioClient`, now returns no result for the `HelioClient` in this case.
The changelog.

2024-02-13 08:30 UTC, samaloney commented
Yea I think I mentioned in the issue it would be better to handle it in general but I didn't see anywhere obvious it could go at first look.

2024-02-13 22:14 UTC, nabobalis commented on changelog/7446.bugfix.rst
> +Fix a bug which caused :meth:`~sunpy.net.Fido.search` to crash due to SSL certificate verification error for the `~sunpy.net.helio.HECClient` now returns no results and logs a warning in this case.
```suggestion
Fix a bug which caused ``Fido.search`` to crash due to SSL certificate verification error for the `~sunpy.net.helio.HECClient` now returns no results and logs a warning in this case.
```

2024-02-13 22:33 UTC, merged