Updates Sunpy core with package template
sunpy/sunpy pull request #7494
Opened 2024-03-12 21:15 UTC by CyclingNinja

* Adds `.cruft.json` 
* General editing and compliance with new package template

2024-03-13 10:36 UTC, Cadair commented on .ruff.toml
> +  "E402",  # Module imports not at top of file
This rule should only apply to conf.py

2024-03-13 11:13 UTC, Cadair approved these changes

2024-03-13 11:14 UTC, CyclingNinja commented
pre-commit.ci autofix

2024-03-13 11:49 UTC, CyclingNinja commented
pre-commit.ci autofox

2024-03-14 13:26 UTC, wtbarnes approved these changes
I am not the most qualified to review this, but this all looks good to me.

2024-03-20 17:24 UTC, Cadair commented
I think the remaining todo here is that the oldestdeps build is broken.

2024-03-20 21:42 UTC, nabobalis approved these changes

2024-03-22 05:25 UTC, nabobalis requested changes
blocking until oldest deps is fixed

2024-04-09 16:00 UTC, Cadair commented
The oldestdeps build is also failing on main, so I think that this is good to go.

2024-04-09 16:15 UTC, nabobalis approved these changes

2024-04-09 16:15 UTC, nabobalis commented on sunpy/tests/__init__.py
> +"""
Does this need to be here?

2024-04-09 16:15 UTC, merged