Monkey patch get_ftp_size with dummy in SRS client
sunpy/sunpy pull request #7521
Opened 2024-03-22 20:09 UTC by nabobalis

Supersedes https://github.com/sunpy/sunpy/pull/7081

Just adds a log check for the patch.

2024-03-26 04:14 UTC, nabobalis commented on sunpy/net/dataretriever/sources/tests/test_noaa.py
> +    assert "aioftp.errors.StatusCodeError: Waiting for ('2xx',) but got 550 [' Permission denied.']" not in caplog.text
This would fail before the patch.

2024-04-04 13:46 UTC, Cadair requested changes
I hate this. This is *so ugly*, surely there's a better way?

Let me have a look into parfive and a think.

2024-04-04 14:09 UTC, Cadair commented
I have opened https://github.com/Cadair/parfive/pull/148 as an alternative to this.

2024-04-04 16:00 UTC, closed without merging

2024-04-04 16:00 UTC, nabobalis commented
So do we need to make changes in sunpy?

2024-04-04 16:01 UTC, Cadair commented
no, just update parfive once I have done a release.