missing figure dec
sunpy/sunpy pull request #7574
Opened 2024-04-16 20:40 UTC by nabobalis

2024-04-16 21:16 UTC, nabobalis commented on sunpy/map/tests/test_reproject_to.py
> +@figure_test
I get that these are not standard figure tests but I still think they should be marked as such.

2024-04-17 14:46 UTC, ayshih requested changes
I'm certain that swapping the order of the decorators makes no difference for the issue that was encountered in CI, so I'd like those swaps to be reverted to keep the Git history more clean.

2024-04-17 14:46 UTC, ayshih commented on sunpy/image/tests/test_transform.py
> +@pytest.mark.filterwarnings("ignore:.*bug in the implementation of scikit-image")
Revert this because it makes no difference

2024-04-17 14:46 UTC, ayshih commented on sunpy/map/tests/test_mapbase.py
> +@pytest.mark.parametrize('method', _rotation_registry.keys())
Revert this because it makes no difference

2024-04-17 14:47 UTC, nabobalis commented on sunpy/map/tests/test_mapbase.py
> +@pytest.mark.parametrize('method', _rotation_registry.keys())
```suggestion
@pytest.mark.parametrize('method', _rotation_registry.keys())
@figure_test
```

2024-04-17 14:47 UTC, nabobalis commented on sunpy/image/tests/test_transform.py
> +@pytest.mark.filterwarnings("ignore:.*bug in the implementation of scikit-image")
```suggestion
@pytest.mark.filterwarnings("ignore:.*bug in the implementation of scikit-image")
@figure_test
```

2024-04-17 15:37 UTC, ayshih approved these changes

2024-04-17 15:37 UTC, merged