Parse DN correctly in header helper
sunpy/sunpy pull request #7730
Opened 2024-07-16 05:00 UTC by wtbarnes

After #7585, "DN" is now correctly handled by `GenericMap`. However, the header helper was still applying strict checking against the FITS standard when parsing the unit string, meaning one could not pass `unit='DN'` into the header helper. This fixes this bug by pulling the unit parsing logic out of `GenericMap` so it can be used in the header helper as well.

2024-07-16 05:07 UTC, nabobalis approved these changes

2024-07-16 05:10 UTC, wtbarnes commented
Wait...this does not do what I want it to do...

2024-07-16 05:14 UTC, nabobalis commented
> Wait...this does not do what I want it to do...
> 
> `_parse_fits_unit` still returns a `Unit`. It needs to be a string. Maybe this is not the right approach.

Time for a second method

2024-07-16 05:15 UTC, nabobalis requested changes
CI is very broken

2024-07-16 05:32 UTC, wtbarnes commented
Oops I forgot it was used other places.

2024-07-18 05:25 UTC, nabobalis commented on sunpy/map/tests/test_header_helper.py
> -
This line should be added back.

2024-07-18 05:25 UTC, nabobalis commented on sunpy/map/tests/test_header_helper.py
> +def test_unit_handles_dn(input_unit, output_string, map_data, hpc_coord):
```suggestion
def test_make_fitswcs_header_handles_dn(input_unit, output_string, map_data, hpc_coord):
```

2024-07-18 05:25 UTC, nabobalis approved these changes

2024-07-18 05:32 UTC, nabobalis commented
setuptools 71.0.1 came out 3 hours ago and broke things, we can pin out that verison.

2024-07-18 06:26 UTC, wtbarnes commented
Oh lovely. I was wondering what in the world was happening.

2024-07-18 14:25 UTC, Cadair commented
you broke it: https://github.com/sunpy/sunpy/actions/runs/9992411608/job/27617589005?pr=7730#step:10:757

2024-07-18 14:43 UTC, wtbarnes commented
> you broke it: https://github.com/sunpy/sunpy/actions/runs/9992411608/job/27617589005?pr=7730#step:10:757

How is that possible

2024-07-18 15:21 UTC, nabobalis commented
It needs to point to the api link and not the import. Is my guess.

2024-07-18 15:22 UTC, nabobalis commented on changelog/7730.bugfix.rst
> +Fixed a bug where "DN" was not able to be parsed by `~sunpy.map.make_fitswcs_header` due to strict checking
```suggestion
Fixed a bug where "DN" was not able to be parsed by `~sunpy.map.header_helper.make_fitswcs_header` due to strict checking
```

2024-07-18 15:22 UTC, nabobalis commented on changelog/7730.bugfix.rst
> +Fixed a bug where "DN" was not able to be parsed by `~sunpy.map.header_helper.make_fitswcs_header` due to strict checking
Hopefully this will work

2024-07-18 16:29 UTC, wtbarnes commented on changelog/7730.bugfix.rst
> +Fixed a bug where "DN" was not able to be parsed by `~sunpy.map.header_helper.make_fitswcs_header` due to strict checking
Ah got it. Thanks!

2024-07-18 16:30 UTC, merged