some docs fixes (replacing old links with new one )
sunpy/sunpy pull request #7762
Opened 2024-07-29 06:48 UTC by Sauravroy34

for #7761

2024-07-29 13:48 UTC, ayshih requested changes
In addition, I'm of the opinion that we should outright remove the references to Anaconda.

2024-07-29 13:48 UTC, ayshih commented on docs/dev_guide/contents/newcomers.rst
> +* `Astropy Dev Workflow <https://kbarbary-astropy.readthedocs.io/en/latest/development/workflow/development_workflow.html>`_
```suggestion
```

2024-07-29 13:48 UTC, ayshih commented on docs/dev_guide/contents/newcomers.rst
> +* `Astropy Dev environment <https://docs.astropy.org/en/latest/development/quickstart.html>`_
```suggestion
* `Astropy Contributing Quickstart <https://docs.astropy.org/en/latest/development/quickstart.html>`_
```

2024-07-29 13:48 UTC, ayshih commented on docs/dev_guide/contents/newcomers.rst
> +* `Astropy Pull Request Example <https://docs.astropy.org/en/latest/development/git_edit_workflow_examples.html>`_
```suggestion
* `Astropy Contribution Example <https://docs.astropy.org/en/latest/development/git_edit_workflow_examples.html>`_
```

2024-07-29 13:48 UTC, ayshih commented on docs/dev_guide/contents/newcomers.rst
> +* `Astropy Dev Workflow <https://kbarbary-astropy.readthedocs.io/en/latest/development/workflow/development_workflow.html>`_
This page doesn't exist anymore.  We definitely shouldn't link to someone else's rendering of super-old Astropy docs.

2024-07-29 15:18 UTC, nabobalis commented on docs/dev_guide/contents/newcomers.rst
> +* `Astropy Contribution Example <https://docs.astropy.org/en/latest/development/git_edit_workflow_examples.html>`_
```suggestion
* `Astropy Contributing Quickstart <https://docs.astropy.org/en/latest/development/quickstart.html>`__
* `Astropy Contribution Example <https://docs.astropy.org/en/latest/development/git_edit_workflow_examples.html>`__
```

2024-07-30 06:08 UTC, nabobalis commented on docs/dev_guide/contents/newcomers.rst
>  .. _miniconda: https://conda.io/en/latest/miniconda.html
```suggestion
.. _miniforge: hhttps://github.com/conda-forge/miniforge?tab=readme-ov-file#download
```

2024-07-30 06:08 UTC, nabobalis commented on docs/dev_guide/contents/newcomers.rst
> +In order to start coding you will need a local Python environment and we would recommend using Anaconda or `miniconda`_ (shortened to conda from here on).
```suggestion
In order to start coding you will need a local Python environment and we would recommend using `miniforge`_ (shortened to conda from here on).
```

2024-07-30 14:29 UTC, ayshih approved these changes
There's one more reference to Anaconda to remove on line 175 of `newcomers.rst`, otherwise, looks good to me

2024-07-30 18:38 UTC, nabobalis commented
Thanks for the PR @Sauravroy34

2024-07-30 18:56 UTC, merged