Add linkcheck to tox + CI + fix urls
sunpy/sunpy pull request #7766
Opened 2024-07-30 20:29 UTC by nabobalis

2024-08-01 15:35 UTC, nabobalis commented on tox.ini
> +    sphinx-build
It errored for me locally.

2024-08-01 15:35 UTC, nabobalis commented on .github/workflows/ci.yml
> +          coverage: ''
```suggestion
```

2024-08-01 15:35 UTC, nabobalis commented on .github/workflows/ci.yml
> +      coverage: ''
Does it matter for the cronjobs for line coverage?

2024-08-01 15:36 UTC, nabobalis commented on tox.ini
> +    sphinx-build
```suggestion
```

2024-08-01 16:48 UTC, nabobalis commented
The job will always fail, I cant work out how to stop it careing about the stability rst file.

2024-08-05 11:14 UTC, Cadair commented on docs/conf.py
> +linkcheck_exclude_documents = ["reference/stability.rst"]
```suggestion
linkcheck_exclude_documents = ["stability.rst"]
```

2024-08-05 15:13 UTC, nabobalis commented on .github/workflows/ci.yml
> +      coverage: ''
I will delete the line instead.

2024-08-05 15:13 UTC, nabobalis commented
How I missed the linkcheck_exclude_documents I will never know.

2024-08-05 15:14 UTC, nabobalis commented on .github/workflows/ci.yml
> +      coverage: ''
```suggestion
```

2024-08-05 15:47 UTC, Cadair commented
I can't make it work though lol

2024-08-08 00:56 UTC, nabobalis commented on docs/conf.py
> +        source.remove(file)
It was a moon shot and I misssed.

2024-08-14 16:15 UTC, ayshih requested changes

2024-08-14 16:15 UTC, ayshih commented on docs/conf.py
> +    lol
I'm not going to object on the function name, but there needs to be a docstring that explains this all

2024-08-14 16:19 UTC, wtbarnes requested changes

2024-08-14 16:19 UTC, wtbarnes commented on docs/conf.py
> +def lol(app, docname, source):
This function removes the unrendered parts of the jinja templates. I think the name should reflect that.

2024-08-14 16:19 UTC, wtbarnes commented on docs/dev_guide/contents/newcomers.rst
> +    As an example, `Standford's guidance <https://otl.stanford.edu/software>`__ allows someone to contribute and open source their code.
```suggestion
    As an example, `Stanford's guidance <https://otl.stanford.edu/software>`__ allows someone to contribute and open source their code.
```

2024-08-14 16:19 UTC, wtbarnes commented on docs/conf.py
> +def lol(app, docname, source):
And should include a description

2024-08-14 18:43 UTC, wtbarnes commented
I think the test fail is real. It looks like the numpy strings and floats are not being rendered as expected as strings.

2024-08-14 20:21 UTC, nabobalis commented
> I think the test fail is real. It looks like the numpy strings and floats are not being rendered as expected as strings.

You mean the online tests? Yes that is known, something is downgrading numpy to <2 and breaking those tests.

2024-08-15 15:22 UTC, alasdairwilson approved these changes
This seems fine for me now.

2024-08-15 15:22 UTC, alasdairwilson commented on docs/dev_guide/contents/newcomers.rst
>      If not, `OSS-Watch <http://oss-watch.ac.uk/resources/contributing>`__ summaries what you will need to check and who to ask, however this resource is aimed at a UK readers.
```suggestion
    If not, `OSS-Watch <http://oss-watch.ac.uk/resources/contributing>`__ summarises what you will need to check and who to ask, however this resource is aimed at a UK readers.
```

2024-08-15 15:22 UTC, alasdairwilson commented on sunpy/image/resample.py
> +    Re-shape the two dimension input image into a four dimensional array
```suggestion
    Re-shape the two-dimensional input image into a four-dimensional array
```

2024-08-15 15:24 UTC, alasdairwilson commented on sunpy/net/jsoc/jsoc.py
> +    The full list of ``Series`` is available through this `site <http://jsoc.stanford.edu>`__.
Did you want to link direct to the page here?
```suggestion
    The full list of ``Series`` is available via ` this page <http://jsoc.stanford.edu/JsocSeries_DataProducts_map.html>`__.
```

2024-08-15 18:23 UTC, alasdairwilson approved these changes

2024-08-15 18:59 UTC, ayshih approved these changes
Just one suggestion

2024-08-15 18:59 UTC, ayshih commented on examples/units_and_coordinates/spice.py
> +* `Parker Solar Probe <https://psp-gateway.jhuapl.edu/>`__
```suggestion
* `Parker Solar Probe <https://psp-gateway.jhuapl.edu/website/Ancillary/SclkFiles>`__
```

2024-08-15 21:30 UTC, wtbarnes approved these changes

2024-08-15 23:06 UTC, merged