Adds Support to `datetime.timedelta` in `sunpy.time.TimeRange.extend`
sunpy/sunpy pull request #7931
Opened 2024-12-15 10:39 UTC by ankitkhushwaha

## PR Description
 
This pr
- [x]  Add Support to `datetime.timedelta` in `sunpy.time.TimeRange.extend`
- [x] Add Unit tests
- [ ]  Adds changelog

2024-12-15 19:19 UTC, nabobalis commented
I think this is a deliberate choice in the API. sunpy as a library only wants to support astropy.time.Time and astropy.time.TimeDelta across the library. 

But I will let the @sunpy/sunpy-maintainers decide.

2025-01-01 17:35 UTC, nabobalis commented on sunpy/time/tests/test_timerange.py
> +    start, end = datetime(2012, 1, 1), datetime(2012, 1, 10)
```suggestion
def test_extend_end_start():
    # Checks when start + delta_1 > end + delta_2
    start, end = datetime(2012, 1, 1), datetime(2012, 1, 10)
```

2025-01-08 17:49 UTC, Cadair commented on sunpy/time/timerange.py
> -        # TODO: Support datetime.timedelta
Thanks for this PR @ankitkhushwaha, we spoke about this at the community meeting today and came to the conclusion as we support `datetime.timedelta` and `astropy.units.Quantity` in the `__init__` of this class we should support it here.

Would you be ok to add support for Quantity objects as well? See this code in the `__init__`: https://github.com/sunpy/sunpy/blob/main/sunpy/time/timerange.py#L111-L125

2025-01-10 11:06 UTC, ankitkhushwaha commented on sunpy/time/timerange.py
> -        # TODO: Support datetime.timedelta
Hey @Cadair, actually by default `astropy.units.Quantity` is consistent with `astropy.time.TimeDelta`, so the existing function already supports `astropy.units.Quantity`.
I have added the tests for that test cases.

2025-01-10 14:55 UTC, ayshih requested changes

2025-01-10 14:55 UTC, ayshih commented on changelog/7931.feature.rst
> +Now :meth:`~sunpy.time.TimeRange.extend` supports inputs of type `datetime.timedelta` and `astropy.units.Quantity`g.
```suggestion
:meth:`~sunpy.time.TimeRange.extend` can now accept inputs of type `datetime.timedelta` and `astropy.units.Quantity`.
```

2025-01-10 14:55 UTC, ayshih commented on sunpy/time/tests/test_timerange.py
>      timerange = sunpy.time.TimeRange(tbegin_str, tfin_str)
```suggestion
@pytest.mark.parametrize("delta_1, delta_2", [
    (5*u.s, 10*u.s),
    (5*u.s, delta),
    (delta, 5*u.s),
    (timedelta(1,2,3), timedelta(2,2,3)),
    (timedelta(1,2,3), delta),
    (delta, timedelta(1,2,3)),
])
def test_extend(delta_1, delta_2):
```

2025-01-10 14:55 UTC, ayshih commented on sunpy/time/tests/test_timerange.py
>      assert isinstance(timerange, sunpy.time.TimeRange)
```suggestion
```

2025-01-10 14:55 UTC, ayshih commented on sunpy/time/tests/test_timerange.py
> +    delta_1, delta_2 = inputs
```suggestion
```

2025-01-10 14:55 UTC, ayshih commented on sunpy/time/timerange.py
> +            dt_end.format = self.dt.format
```suggestion
        dt_start = TimeDelta(dt_start, scale=self._t1.scale) if not isinstance(dt_start, TimeDelta) else dt_start
        dt_end = TimeDelta(dt_end, scale=self._t2.scale) if not isinstance(dt_end, TimeDelta) else dt_end
```
These shouldn't be a need to set the format, but there is a need to set the scale

2025-01-10 14:56 UTC, ayshih commented
My suggested changes to the unit tests may be a bit confusing, but I'm merging two tests and cleaning up the parametrization approach.

2025-01-10 16:16 UTC, ankitkhushwaha commented
implemented the requested changes.

2025-01-11 04:53 UTC, ankitkhushwaha commented
> Sorry to do this to you, but after reviewing your PR, I realized that we ought to rename this method (see the just-merged #8008). Please rebase your PR off of the latest `main`.

no worries.
i have solved the merge conflict

2025-01-11 05:31 UTC, nabobalis commented on changelog/7931.feature.rst
> +:meth:`~sunpy.time.TimeRange.extend` can now accept inputs of type `datetime.timedelta` and `astropy.units.Quantity`.
```suggestion
:meth:`~sunpy.time.TimeRange.shift` can now accept inputs of type `datetime.timedelta` and `astropy.units.Quantity`.
```

2025-02-04 14:07 UTC, ayshih requested changes
Also, add a second changelog entry, categorized as `bugfix`, for the fact that `shift()` now swaps the start and end times if needed.  (Before anyone asks, I am not inclined to actually backport this bugfix.)

2025-02-04 14:07 UTC, ayshih commented on changelog/7931.feature.rst
> +:meth:`~sunpy.time.TimeRange.shift` can now accept inputs of type `datetime.timedelta` and `astropy.units.Quantity`.
```suggestion
:meth:`sunpy.time.TimeRange.shift` can now accept inputs of type `datetime.timedelta` and `astropy.units.Quantity`.
```

2025-02-04 14:07 UTC, ayshih commented on sunpy/time/tests/test_timerange.py
> +    (5*u.s, 10*u.s),
```suggestion
@pytest.mark.parametrize(("delta_1", "delta_2"), [
    (delta, delta),
    (-delta, delta),
    (5*u.s, 10*u.s),
```

2025-02-04 17:45 UTC, ankitkhushwaha commented
Hey, i have added the bugfix changelog, and updated the tests.

2025-02-04 19:04 UTC, ayshih approved these changes
I revised the bugfix changelog entry, but otherwise looks good to me.  Thanks!

2025-02-04 19:04 UTC, ayshih commented on changelog/7931.bugfix.rst
> +:meth:`sunpy.time.TimeRange.shift` now adjusts the TimeRange to start or end at the nearest bound of the timeseries if the input timerange is out of bound.
```suggestion
Fixed a time-ordering bug in :meth:`sunpy.time.TimeRange.shift` when the shifted start time is later than than the shifted end time.
```

2025-02-04 19:20 UTC, nabobalis approved these changes

2025-02-04 19:20 UTC, nabobalis commented
I am going to backport this to 6.1 since we have not released it yet.

2025-02-04 19:26 UTC, merged

2025-02-04 19:32 UTC, nabobalis commented
Thanks again @ankitkhushwaha and thanks for the review @ayshih