Adds custom energy bin support for Fermi/GBM TimeSeries
sunpy/sunpy pull request #7943
Opened 2024-12-19 10:32 UTC by ankitkhushwaha

## PR Description

This fixes [#7940](https://github.com/sunpy/sunpy/issues/7940)

To calculate different energy bins 

```
import sunpy.timeseries
from sunpy.data.test import get_test_filepath
from sunpy.tests.helpers import figure_test

fermi_gbm_filepath = get_test_filepath('gbm.fits') 
```

`ts_gbm = sunpy.timeseries.TimeSeries(fermi_gbm_filepath, energy_bands = (12,4,345,54,56,65))`

or

```
ts_gbm = sunpy.timeseries.TimeSeries(fermi_gbm_filepath)
ts_gbm.energy_bins([232,45,77,323])
```

2024-12-19 19:48 UTC, nabobalis commented
@hayesla does something like this solve your original issue?

2024-12-20 02:37 UTC, ankitkhushwaha commented
It give the same new object with modified energy bins
![image](https://github.com/user-attachments/assets/6cc89f99-df01-41be-8454-e7d5321a8cd8)

![image](https://github.com/user-attachments/assets/7cf0f3dc-d6fa-4d7f-9cf6-6aad0a25ed88)

2025-01-01 17:36 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +        ebands = kwargs.get('energy_bands', [4, 15, 25, 50, 100, 300, 800, 2000])
The energy bins should have astropy units attached to them and we would want to enforce that.

2025-01-01 17:37 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +    default bin ranges used:
```suggestion
    Default bin ranges used:
```

2025-01-01 17:37 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +        from sunpy.timeseries.timeseries_factory import TimeSeries
Do we need to do this?

2025-01-01 17:38 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +    _hdulist = None
So this stores the original data when you open the file?

2025-01-02 04:12 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +    _hdulist = None
yes

2025-01-02 04:17 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +        from sunpy.timeseries.timeseries_factory import TimeSeries
This function `energy_bins(cls, energy_bands)` returns The new timeseries with new energy bins , that's why this is needed
I have imported `timeseries` here to prevent circular import

2025-01-02 04:20 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +    _hdulist = None
I feel like there is a trick with __new__ but I can't find a reference.

2025-01-02 09:32 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +        cls._hdulist= hdulist
@nabobalis  This save the hdulist data, that is used for further use

2025-01-02 12:43 UTC, ankitkhushwaha commented
Added the unit support in `energy_bins` input, i created a new custom unit for the data (`u.KeV`)
this pr will handle input cases like 
```
[4*u.eV,7*u.J,8*u.KeV]
[1,2,35,66]*u.KeV
[1,2,35,66]*u.eV
[1,2,35,66]*u.J
```

2025-01-02 16:33 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +        from sunpy.timeseries.timeseries_factory import TimeSeries
I feel like there is a trick with `__new__` but I can't find a reference.

2025-01-02 18:03 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
>          # rebin the 128 energy channels into some summary ranges
This will close the reference of the file

2025-01-02 18:24 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +u.KeV = u.def_unit('KeV', 1000 * u.eV)
There isn't one already?

2025-01-02 18:34 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +u.KeV = u.def_unit('KeV', 1000 * u.eV)
This is composite unit(Kilo electronVolt),  i think that's why it is not
```
>>> import astropy.units as u
>>> u.KeV
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    u.KeV
AttributeError: module 'astropy.units' has no attribute 'KeV'
>>> 
```

2025-01-02 18:39 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +u.KeV = u.def_unit('KeV', 1000 * u.eV)
Can this be defined where its needed?

2025-01-03 16:44 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +            cls._count_data = hdulist[2].data
these are the necessary variable that stores the for creating `timeseries` ,so it can be used by 
`energy_bins()`
i have removed `hdulist` because if it is set to none we can not use that in `energy_bins()`

2025-01-04 04:49 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +            cls._count_data = hdulist[2].data
if the changes are fine,
should i start to write the tests for this?

2025-01-04 04:51 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +        u.KeV = u.def_unit('KeV', 1000 * u.eV)
I think there is a context manager, that might be better.

2025-01-04 04:52 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +            cls._count_data = hdulist[2].data
So what do these provide?

2025-01-04 04:56 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +            cls._count_data = hdulist[2].data
```
cls._energy_bins
cls._count_data
cls._header
``` 
they essentially saves the required data for future use

2025-01-04 06:30 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +            cls._count_data = hdulist[2].data
I see, I honestly do not have a good basis to decide if this is how it should be done.

2025-01-04 07:48 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +            cls._count_data = hdulist[2].data
any suggestion from your side?

2025-01-04 10:35 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +
i shifted the code outside of class ,
this way user can not access this private variables, and will be only for private use

2025-01-04 17:05 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +            cls._count_data = hdulist[2].data
Is that different tho from this?

2025-01-04 17:28 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +    ebands = sorted(ebands)
There was no need to define `u.kev` , 
By mistake i was accessing it using `u.KeV`

2025-01-04 17:31 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +
I think these should be inside the class, they are specific to each individual timseries no?

2025-01-04 18:07 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +
I see, these value will get mixed up incase of 2 GBMSummaryTimeSeries

I think for these variables using __(double underscore) inside class and a comment for their internal use will be fine.

2025-01-05 17:02 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +
hey, i have resolved this issue.

2025-01-05 17:07 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +    __count_data = None
Is this tied to the class and or the instance of the class?

2025-01-05 18:23 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +    __count_data = None
i think they should be specific to each class.

2025-01-05 18:25 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +
these variables will be now specific to each instance

2025-01-05 19:06 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +        # Private instance variables for internal use.
```suggestion
```

2025-01-05 19:07 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +
```suggestion
```

2025-01-05 19:07 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +            # these GBM files have three FITS extensions.
```suggestion
            # These GBM files have three FITS extensions.
```

2025-01-05 19:07 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +            # extn1 - this gives the energy range for each of the 128 energy bins
```suggestion
            # extn1 - Gives the energy range for each of the 128 energy bins
```

2025-01-05 19:08 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +            # extn2 - this contains the data, e.g. counts, exposure time, time of observation
```suggestion
            # extn2 - Contains the data, e.g. counts, exposure time, time of observation
```

2025-01-05 19:08 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +            # extn3 - eclipse times?
```suggestion
            # extn3 - Eclipse times?
```

2025-01-05 19:08 UTC, nabobalis commented
Will need some unit tests and a feature changelog entry

2025-01-06 11:01 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/goes.py
>          """
some of test when exectues this block is triggerd
https://github.com/sunpy/sunpy/blob/62e68dcb99263e65c42e6a8b92fa8b3da61da58a/sunpy/timeseries/timeseries_factory.py#L526-L528

so for different type of input of fermi_gbm file for creating `Timeseries` . so this block can be triggered. so that's why i give **kwargs input in it
`data, meta, units = WidgetType._parse_file(filepath, **kwargs) `, To prevent other tests from failing i made changes in `_parse_file`  of all files in source folder

2025-01-06 11:08 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/tests/test_fermi_gbm.py
> +    assert np.all(ts_gbm_energy_bins__.to_dataframe().columns == col_list)
currently these test only checking the columns list.
any suggestion for the improvements.

2025-01-09 15:35 UTC, hayesla requested changes
Thanks for this PR @ankitkhushwaha !

I have comments in the review.

We shuold also think about what happens if a user passes energy bands that are completely outside the energy range available (i.e. outside whats in energy_bins in the file). For example, GBM provides observations in 4 - 2000 keV bands - however what if someone passed energy_bands = [0, 2]*u.keV? maybe it should raise an error or warning to say this is not within the available energy bins

2025-01-09 16:58 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +        if hdulist:
When we initialize the `GBMSummaryTimeSeries` 
https://github.com/sunpy/sunpy/blob/254152767a0c653a9d9e61ed8516399651ba8d2f/sunpy/timeseries/timeseries_factory.py#L394-L395 gets trigged so `hdulist` is passed in `_parse_hdus`

but when `timeseries` is already initialized , function `def energy_bins(cls, energy_bands = None)`  `hdulist` is set to none , rest of required parameter are passed as kwargs

2025-01-09 17:02 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +        raise UserWarning("'energy_bands' must contain more than one element.")
if user gave only one element as input , we cant define a interval for columns and rest of code wont work even.

2025-01-09 17:05 UTC, hayesla commented on sunpy/timeseries/sources/fermi_gbm.py
> +        raise UserWarning("'energy_bands' must contain more than one element.")
yes, but I mean is it the correct warning to raise, or should it be a ValueError warning instead

2025-01-09 17:08 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +        if ind_start != len(e_center) or ind_end != len(e_center):
When i was testing for the out of bound cases `ind_start, ind_end` reaches to its last value. and we got `Indexerror` for 
` energy_width = (energy_bins["e_max"][ind_end - 1] - energy_bins["e_min"][ind_start])`
so i added the nan values in the data

2025-01-09 17:24 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +        raise UserWarning("'energy_bands' must contain more than one element.")
i think ValueError warning would be better.

2025-01-09 17:31 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +        if ind_start != len(e_center) or ind_end != len(e_center):
> We shuold also think about what happens if a user passes energy bands that are completely outside the energy range available (i.e. outside whats in energy_bins in the file). For example, GBM provides observations in 4 - 2000 keV bands - however what if someone passed energy_bands = [0, 2]*u.keV? maybe it should raise an error or warning to say this is not within the available energy bins

i think if we raise a error then we dont need this line.
But if we warn user `[0, 2]*u.keV` will give input some thing like this 

![image](https://github.com/user-attachments/assets/477a80b0-d5fd-49e9-b5f4-6fa9e133480f)

2025-01-10 18:00 UTC, ankitkhushwaha commented
> We shuold also think about what happens if a user passes energy bands that are completely outside the energy range available (i.e. outside whats in energy_bins in the file). For example, GBM provides observations in 4 - 2000 keV bands - however what if someone passed energy_bands = [0, 2]*u.keV? maybe it should raise an error or warning to say this is not within the available energy bins

```
import sunpy.io._file_tools
from astropy import units as u
import sunpy.timeseries
from sunpy.data.test import get_test_filepath

hdus = sunpy.io._file_tools.read_file(fermi_gbm_filepath)
energy_bins = hdus[1].data
count_data = hdus[2].data
print(energy_bins['e_min'].min())
print(energy_bins['e_max'].max())
```
```
4.246656
2000.0
```

some of fermi gbm files may have different observations  range ,
this code is giving the `min , max observation` present in the file. 
i think it will be better to use these values for defining ranges instead of prefined one `[4, 2000]*u.keV`.

what are your thoughts? @hayesla

2025-01-10 18:20 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +        if ind_start != len(e_center) or ind_end != len(e_center):
> whats this included for? you would want to include the last bin?

Here, the last bin values are filled with nan, because this raises Indexerror for last bin  data
also i have not dropped this because of defined column(they maybe out of bound ranges).

But we can drop the particular column and raising a warning telling that that particular column is dropped because of  Out of bound ranges or last bin value.

2025-01-13 17:48 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +    unit_str = unit.to_string("generic")
this function is taken from 
https://github.com/astropy/astropy/blob/81e9ac2a6e661ee2a67fe49612430ef0f933e9dd/astropy/units/core.py#L1048-L1050

2025-01-26 05:39 UTC, ankitkhushwaha commented
The pull request is ready for review. Please re-review the changes and let me know if anything else is needed.

2025-02-01 22:09 UTC, nabobalis commented on changelog/7943.feature.rst
> +Added a keyword `energy_bands` for creating `sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries` with custom energy bins while initializing it.
Doc build is failing on:

```
<unknown>:7: WARNING: py:func reference target not found: sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries.energy_bins [ref.func]
<unknown>:7: WARNING: py:obj reference target not found: energy_bands [ref.obj]
```

2025-02-01 22:09 UTC, nabobalis commented
The figure hashes need to be updated as well due to the changes.

2025-02-02 05:43 UTC, ankitkhushwaha commented
Hey nabobalis 
 all the required tests are passing now.

2025-02-02 05:47 UTC, ankitkhushwaha commented on changelog/7943.feature.rst
> +Added a keyword `energy_bands` for creating `sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries` with custom energy bins while initializing it.
i think using the same approach as [#6437](https://github.com/sunpy/sunpy/pull/6437/commits/eeb364c22709cbb26ea715141660eb1650a3634e) will fix the docs issue

2025-02-02 17:35 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +import math
Do we need to use math?

2025-02-02 17:43 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +    >>> gbm_ts = gbm.energy_bins([50, 100, 200, 400, 1000] * u.keV)  # doctest: +SKIP
This should be in the examples for energy_bin.

2025-02-02 18:07 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +import math
for
 `energy_bins['e_max'].max()` i rounded it to smallest integer greater than this
in 
`e_min, e_max = round(energy_bins['e_min'].min()), math.ceil(energy_bins['e_max'].max())`

for 1999.34 rounded upto 2000
it will be better for comparing values.

2025-02-02 18:32 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +import math
Why would we not use numpy?

2025-02-02 18:37 UTC, ankitkhushwaha commented on sunpy/timeseries/sources/fermi_gbm.py
> +import math
Oh, I am not aware of that, will change it to use numpy

2025-02-03 03:09 UTC, ankitkhushwaha commented
Requested changes are Implemented.

2025-02-08 04:57 UTC, nabobalis commented on changelog/7943.feature.rst
> +Added a function ``sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries.energy_bins`` to give `sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries` with custom energy bins.
```suggestion
Added a function ``sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries.energy_bins`` to create a new `sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries` with user-specified energy bins.
```

2025-02-08 04:57 UTC, nabobalis commented on changelog/7943.feature.rst
> +Added a keyword ``energy_bands`` for creating `sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries` with custom energy bins while initializing it.
```suggestion
You can now pass a keyword ``energy_bands`` to create a `sunpy.timeseries.sources.fermi_gbm.GBMSummaryTimeSeries` with custom energy bins.
```

2025-02-08 05:05 UTC, nabobalis commented on sunpy/timeseries/sources/fermi_gbm.py
> +    Additionally, GBM timeseries with different energy bins ranges can be calculated as follows.
```suggestion
    Additionally, GBM timeseries with different energy bins ranges can be calculated by using the ``energy_bands`` keyword.
```

2025-07-17 10:52 UTC, ankitkhushwaha commented
Hello, @nabobalis , @hayesla ,
please let me know if there is anything to fix in the PR.

2026-05-27 06:30 UTC, closed without merging